<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class AdultosMayoresSeeder extends Seeder
{
    public function run()
    {
        $adultosMayores = [
            [
                'ipress' => '001234',
                'numero_ficha' => 'AM-001',
                'apellidos' => 'González Pérez',
                'nombres' => 'María Carmen',
                'dni' => '12345678',
                'telefono' => '987654321',
                'fecha_ingreso' => '2024-01-15',
                'fecha_nacimiento' => '1945-03-15',
                'alergias' => 'Penicilina, Polen',
                'adulto_mayor_fragil' => 'No',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'ipress' => '001234',
                'numero_ficha' => 'AM-002',
                'apellidos' => 'Martínez Silva',
                'nombres' => 'José Antonio',
                'dni' => '87654321',
                'telefono' => '987654322',
                'fecha_ingreso' => '2024-02-10',
                'fecha_nacimiento' => '1940-08-22',
                'alergias' => null,
                'adulto_mayor_fragil' => 'Sí',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'ipress' => '001234',
                'numero_ficha' => 'AM-003',
                'apellidos' => 'López Ramírez',
                'nombres' => 'Carmen Rosa',
                'dni' => '11223344',
                'telefono' => '987654323',
                'fecha_ingreso' => '2024-03-05',
                'fecha_nacimiento' => '1950-12-05',
                'alergias' => 'Sulfas',
                'adulto_mayor_fragil' => 'No',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'ipress' => '001234',
                'numero_ficha' => 'AM-004',
                'apellidos' => 'Rodríguez Torres',
                'nombres' => 'Pedro Manuel',
                'dni' => '44556677',
                'telefono' => '987654324',
                'fecha_ingreso' => '2024-03-15',
                'fecha_nacimiento' => '1948-07-20',
                'alergias' => null,
                'adulto_mayor_fragil' => 'No',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'ipress' => '001234',
                'numero_ficha' => 'AM-005',
                'apellidos' => 'Vásquez Herrera',
                'nombres' => 'Ana Lucía',
                'dni' => '55667788',
                'telefono' => '987654325',
                'fecha_ingreso' => '2024-03-20',
                'fecha_nacimiento' => '1955-09-10',
                'alergias' => 'Aspirina',
                'adulto_mayor_fragil' => 'No',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'ipress' => '001234',
                'numero_ficha' => 'AM-006',
                'apellidos' => 'Morales Castro',
                'nombres' => 'Roberto Carlos',
                'dni' => '66778899',
                'telefono' => '987654326',
                'fecha_ingreso' => '2024-04-01',
                'fecha_nacimiento' => '1942-11-18',
                'alergias' => null,
                'adulto_mayor_fragil' => 'Sí',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'ipress' => '001234',
                'numero_ficha' => 'AM-007',
                'apellidos' => 'Flores Mendoza',
                'nombres' => 'Elena Rosa',
                'dni' => '77889900',
                'telefono' => '987654327',
                'fecha_ingreso' => '2024-04-05',
                'fecha_nacimiento' => '1946-06-25',
                'alergias' => 'Yodo, Mariscos',
                'adulto_mayor_fragil' => 'No',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'ipress' => '001234',
                'numero_ficha' => 'AM-008',
                'apellidos' => 'Chávez Quispe',
                'nombres' => 'Miguel Ángel',
                'dni' => '88990011',
                'telefono' => '987654328',
                'fecha_ingreso' => '2024-04-10',
                'fecha_nacimiento' => '1951-02-14',
                'alergias' => null,
                'adulto_mayor_fragil' => 'No',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'ipress' => '001234',
                'numero_ficha' => 'AM-009',
                'apellidos' => 'Sandoval Paredes',
                'nombres' => 'Luz Marina',
                'dni' => '99001122',
                'telefono' => '987654329',
                'fecha_ingreso' => '2024-04-12',
                'fecha_nacimiento' => '1949-04-30',
                'alergias' => 'Contraste yodado',
                'adulto_mayor_fragil' => 'Sí',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'ipress' => '001234',
                'numero_ficha' => 'AM-010',
                'apellidos' => 'Reyes Vargas',
                'nombres' => 'Fernando Luis',
                'dni' => '10111213',
                'telefono' => '987654330',
                'fecha_ingreso' => '2024-04-15',
                'fecha_nacimiento' => '1944-08-07',
                'alergias' => null,
                'adulto_mayor_fragil' => 'No',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'ipress' => '001234',
                'numero_ficha' => 'AM-011',
                'apellidos' => 'Huamán Quispe',
                'nombres' => 'Teresa Elvira',
                'dni' => '14151617',
                'telefono' => '987654331',
                'fecha_ingreso' => '2024-04-18',
                'fecha_nacimiento' => '1947-01-22',
                'alergias' => 'Sulfonamidas',
                'adulto_mayor_fragil' => 'Sí',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'ipress' => '001234',
                'numero_ficha' => 'AM-012',
                'apellidos' => 'Campos Rivera',
                'nombres' => 'Alberto Jesús',
                'dni' => '18192021',
                'telefono' => '987654332',
                'fecha_ingreso' => '2024-04-20',
                'fecha_nacimiento' => '1943-10-15',
                'alergias' => null,
                'adulto_mayor_fragil' => 'No',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'ipress' => '001234',
                'numero_ficha' => 'AM-013',
                'apellidos' => 'Aguilar Sánchez',
                'nombres' => 'Rosa María',
                'dni' => '22232425',
                'telefono' => '987654333',
                'fecha_ingreso' => '2024-04-22',
                'fecha_nacimiento' => '1952-05-08',
                'alergias' => 'Latex, Penicilina',
                'adulto_mayor_fragil' => 'No',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'ipress' => '001234',
                'numero_ficha' => 'AM-014',
                'apellidos' => 'Córdova Mamani',
                'nombres' => 'Juan Carlos',
                'dni' => '26272829',
                'telefono' => '987654334',
                'fecha_ingreso' => '2024-04-25',
                'fecha_nacimiento' => '1941-12-03',
                'alergias' => null,
                'adulto_mayor_fragil' => 'Sí',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'ipress' => '001234',
                'numero_ficha' => 'AM-015',
                'apellidos' => 'Medina Ochoa',
                'nombres' => 'Gladys Noemí',
                'dni' => '30313233',
                'telefono' => '987654335',
                'fecha_ingreso' => '2024-04-28',
                'fecha_nacimiento' => '1954-03-17',
                'alergias' => 'Morfina',
                'adulto_mayor_fragil' => 'No',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'ipress' => '001234',
                'numero_ficha' => 'AM-016',
                'apellidos' => 'Castillo Fernández',
                'nombres' => 'Víctor Hugo',
                'dni' => '34353637',
                'telefono' => '987654336',
                'fecha_ingreso' => '2024-05-02',
                'fecha_nacimiento' => '1946-07-11',
                'alergias' => null,
                'adulto_mayor_fragil' => 'No',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'ipress' => '001234',
                'numero_ficha' => 'AM-017',
                'apellidos' => 'Villanueva Cruz',
                'nombres' => 'Margarita Isabel',
                'dni' => '38394041',
                'telefono' => '987654337',
                'fecha_ingreso' => '2024-05-05',
                'fecha_nacimiento' => '1948-09-28',
                'alergias' => 'Codeína',
                'adulto_mayor_fragil' => 'Sí',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'ipress' => '001234',
                'numero_ficha' => 'AM-018',
                'apellidos' => 'Espinoza Delgado',
                'nombres' => 'Ricardo Manuel',
                'dni' => '42434445',
                'telefono' => '987654338',
                'fecha_ingreso' => '2024-05-08',
                'fecha_nacimiento' => '1950-11-14',
                'alergias' => null,
                'adulto_mayor_fragil' => 'No',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'ipress' => '001234',
                'numero_ficha' => 'AM-019',
                'apellidos' => 'Hidalgo Rojas',
                'nombres' => 'Silvia Patricia',
                'dni' => '46474849',
                'telefono' => '987654339',
                'fecha_ingreso' => '2024-05-10',
                'fecha_nacimiento' => '1945-04-19',
                'alergias' => 'Anestésicos locales',
                'adulto_mayor_fragil' => 'Sí',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'ipress' => '001234',
                'numero_ficha' => 'AM-020',
                'apellidos' => 'Ramos Gutiérrez',
                'nombres' => 'Oswaldo Enrique',
                'dni' => '50515253',
                'telefono' => '987654340',
                'fecha_ingreso' => '2024-05-12',
                'fecha_nacimiento' => '1953-06-02',
                'alergias' => null,
                'adulto_mayor_fragil' => 'No',
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ];

        DB::table('adultos_mayores')->insert($adultosMayores);
    }
}