<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CitasSeeder extends Seeder
{
    public function run()
    {
        $citas = [
            [
                'adulto_mayor_id' => 1,
                'fecha' => '2024-01-15',
                'medico' => 'Dr. Ana Rodríguez',
                'enfermera' => 'Enf. Carmen Silva',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'adulto_mayor_id' => 1,
                'fecha' => '2024-02-15',
                'medico' => 'Dr. Ana Rodríguez',
                'enfermera' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'adulto_mayor_id' => 2,
                'fecha' => '2024-02-10',
                'medico' => 'Dr. Luis García',
                'enfermera' => 'Enf. María Torres',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'adulto_mayor_id' => 2,
                'fecha' => '2024-03-10',
                'medico' => 'Dr. Luis García',
                'enfermera' => 'Enf. María Torres',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'adulto_mayor_id' => 3,
                'fecha' => '2024-03-05',
                'medico' => null,
                'enfermera' => 'Enf. Carmen Silva',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'adulto_mayor_id' => 4,
                'fecha' => '2024-03-15',
                'medico' => 'Dr. Pedro Mendoza',
                'enfermera' => 'Enf. Rosa López',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'adulto_mayor_id' => 5,
                'fecha' => '2024-03-25',
                'medico' => 'Dr. Ana Rodríguez',
                'enfermera' => 'Enf. Carmen Silva',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'adulto_mayor_id' => 3,
                'fecha' => '2024-04-10',
                'medico' => 'Dr. Carlos Vega',
                'enfermera' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'adulto_mayor_id' => 6,
                'fecha' => '2024-04-01',
                'medico' => 'Dr. Luis García',
                'enfermera' => 'Enf. María Torres',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'adulto_mayor_id' => 6,
                'fecha' => '2024-04-15',
                'medico' => 'Dr. Luis García',
                'enfermera' => 'Enf. María Torres',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'adulto_mayor_id' => 7,
                'fecha' => '2024-04-05',
                'medico' => 'Dr. Ana Rodríguez',
                'enfermera' => 'Enf. Carmen Silva',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'adulto_mayor_id' => 8,
                'fecha' => '2024-04-10',
                'medico' => null,
                'enfermera' => 'Enf. Rosa López',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'adulto_mayor_id' => 9,
                'fecha' => '2024-04-12',
                'medico' => 'Dr. Pedro Mendoza',
                'enfermera' => 'Enf. María Torres',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'adulto_mayor_id' => 9,
                'fecha' => '2024-04-26',
                'medico' => 'Dr. Pedro Mendoza',
                'enfermera' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'adulto_mayor_id' => 10,
                'fecha' => '2024-04-15',
                'medico' => 'Dr. Carlos Vega',
                'enfermera' => 'Enf. Carmen Silva',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'adulto_mayor_id' => 11,
                'fecha' => '2024-04-18',
                'medico' => 'Dr. Luis García',
                'enfermera' => 'Enf. María Torres',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'adulto_mayor_id' => 11,
                'fecha' => '2024-05-02',
                'medico' => 'Dr. Luis García',
                'enfermera' => 'Enf. María Torres',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'adulto_mayor_id' => 12,
                'fecha' => '2024-04-20',
                'medico' => 'Dr. Pedro Mendoza',
                'enfermera' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'adulto_mayor_id' => 13,
                'fecha' => '2024-04-22',
                'medico' => null,
                'enfermera' => 'Enf. Rosa López',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'adulto_mayor_id' => 14,
                'fecha' => '2024-04-25',
                'medico' => 'Dr. Luis García',
                'enfermera' => 'Enf. María Torres',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'adulto_mayor_id' => 14,
                'fecha' => '2024-05-09',
                'medico' => 'Dr. Luis García',
                'enfermera' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'adulto_mayor_id' => 15,
                'fecha' => '2024-04-28',
                'medico' => null,
                'enfermera' => 'Enf. Carmen Silva',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'adulto_mayor_id' => 16,
                'fecha' => '2024-05-02',
                'medico' => 'Dr. Ana Rodríguez',
                'enfermera' => 'Enf. Rosa López',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'adulto_mayor_id' => 17,
                'fecha' => '2024-05-05',
                'medico' => 'Dr. Pedro Mendoza',
                'enfermera' => 'Enf. María Torres',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'adulto_mayor_id' => 17,
                'fecha' => '2024-05-19',
                'medico' => 'Dr. Pedro Mendoza',
                'enfermera' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'adulto_mayor_id' => 18,
                'fecha' => '2024-05-08',
                'medico' => null,
                'enfermera' => 'Enf. Carmen Silva',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'adulto_mayor_id' => 19,
                'fecha' => '2024-05-10',
                'medico' => 'Dr. Carlos Vega',
                'enfermera' => 'Enf. Rosa López',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'adulto_mayor_id' => 19,
                'fecha' => '2024-05-24',
                'medico' => 'Dr. Carlos Vega',
                'enfermera' => 'Enf. Rosa López',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'adulto_mayor_id' => 20,
                'fecha' => '2024-05-12',
                'medico' => 'Dr. Ana Rodríguez',
                'enfermera' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ];

        DB::table('citas')->insert($citas);
    }
}