<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class EnfermedadesSeeder extends Seeder
{
    public function run()
    {
        $enfermedades = [
            [
                'adulto_mayor_id' => 1,
                'obesidad' => false,
                'dislipidemia' => true,
                'hipertension_arterial' => true,
                'diabetes_mellitus' => false,
                'erc' => false,
                'osteoartrosis' => true,
                'asma' => false,
                'epoc' => false,
                'itg' => false,
                'sindrome_metabolico' => false,
                'otros' => null,
                'visare_numero' => 12345,
                'visare_fecha' => '2024-01-20',
                'estadio_1a_3a_numero' => null,
                'estadio_1a_3a_fecha' => null,
                'estadio_3b_5_numero' => null,
                'estadio_3b_5_fecha' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'adulto_mayor_id' => 2,
                'obesidad' => true,
                'dislipidemia' => true,
                'hipertension_arterial' => true,
                'diabetes_mellitus' => true,
                'erc' => true,
                'osteoartrosis' => false,
                'asma' => false,
                'epoc' => false,
                'itg' => false,
                'sindrome_metabolico' => true,
                'otros' => 'Insuficiencia cardíaca',
                'visare_numero' => 12346,
                'visare_fecha' => '2024-02-15',
                'estadio_1a_3a_numero' => 98765,
                'estadio_1a_3a_fecha' => '2024-02-16',
                'estadio_3b_5_numero' => null,
                'estadio_3b_5_fecha' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'adulto_mayor_id' => 3,
                'obesidad' => false,
                'dislipidemia' => false,
                'hipertension_arterial' => false,
                'diabetes_mellitus' => false,
                'erc' => false,
                'osteoartrosis' => true,
                'asma' => true,
                'epoc' => false,
                'itg' => false,
                'sindrome_metabolico' => false,
                'otros' => null,
                'visare_numero' => null,
                'visare_fecha' => null,
                'estadio_1a_3a_numero' => null,
                'estadio_1a_3a_fecha' => null,
                'estadio_3b_5_numero' => null,
                'estadio_3b_5_fecha' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'adulto_mayor_id' => 4,
                'obesidad' => false,
                'dislipidemia' => true,
                'hipertension_arterial' => true,
                'diabetes_mellitus' => false,
                'erc' => false,
                'osteoartrosis' => false,
                'asma' => false,
                'epoc' => true,
                'itg' => false,
                'sindrome_metabolico' => false,
                'otros' => 'Hipotiroidismo',
                'visare_numero' => 12347,
                'visare_fecha' => '2024-03-20',
                'estadio_1a_3a_numero' => null,
                'estadio_1a_3a_fecha' => null,
                'estadio_3b_5_numero' => null,
                'estadio_3b_5_fecha' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'adulto_mayor_id' => 5,
                'obesidad' => false,
                'dislipidemia' => false,
                'hipertension_arterial' => false,
                'diabetes_mellitus' => false,
                'erc' => false,
                'osteoartrosis' => true,
                'asma' => false,
                'epoc' => false,
                'itg' => false,
                'sindrome_metabolico' => false,
                'otros' => null,
                'visare_numero' => null,
                'visare_fecha' => null,
                'estadio_1a_3a_numero' => null,
                'estadio_1a_3a_fecha' => null,
                'estadio_3b_5_numero' => null,
                'estadio_3b_5_fecha' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'adulto_mayor_id' => 6,
                'obesidad' => false,
                'dislipidemia' => true,
                'hipertension_arterial' => true,
                'diabetes_mellitus' => true,
                'erc' => true,
                'osteoartrosis' => true,
                'asma' => false,
                'epoc' => true,
                'itg' => false,
                'sindrome_metabolico' => true,
                'otros' => 'Fibrilación auricular, Insuficiencia renal crónica',
                'visare_numero' => 12348,
                'visare_fecha' => '2024-04-02',
                'estadio_1a_3a_numero' => null,
                'estadio_1a_3a_fecha' => null,
                'estadio_3b_5_numero' => 87654,
                'estadio_3b_5_fecha' => '2024-04-03',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'adulto_mayor_id' => 7,
                'obesidad' => true,
                'dislipidemia' => true,
                'hipertension_arterial' => true,
                'diabetes_mellitus' => false,
                'erc' => false,
                'osteoartrosis' => false,
                'asma' => false,
                'epoc' => false,
                'itg' => true,
                'sindrome_metabolico' => true,
                'otros' => 'Hipotiroidismo',
                'visare_numero' => 12349,
                'visare_fecha' => '2024-04-06',
                'estadio_1a_3a_numero' => null,
                'estadio_1a_3a_fecha' => null,
                'estadio_3b_5_numero' => null,
                'estadio_3b_5_fecha' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'adulto_mayor_id' => 8,
                'obesidad' => false,
                'dislipidemia' => false,
                'hipertension_arterial' => false,
                'diabetes_mellitus' => false,
                'erc' => false,
                'osteoartrosis' => true,
                'asma' => false,
                'epoc' => false,
                'itg' => false,
                'sindrome_metabolico' => false,
                'otros' => null,
                'visare_numero' => null,
                'visare_fecha' => null,
                'estadio_1a_3a_numero' => null,
                'estadio_1a_3a_fecha' => null,
                'estadio_3b_5_numero' => null,
                'estadio_3b_5_fecha' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'adulto_mayor_id' => 9,
                'obesidad' => true,
                'dislipidemia' => true,
                'hipertension_arterial' => true,
                'diabetes_mellitus' => true,
                'erc' => false,
                'osteoartrosis' => true,
                'asma' => false,
                'epoc' => false,
                'itg' => false,
                'sindrome_metabolico' => true,
                'otros' => 'Depresión, Osteoporosis',
                'visare_numero' => 12350,
                'visare_fecha' => '2024-04-13',
                'estadio_1a_3a_numero' => 56789,
                'estadio_1a_3a_fecha' => '2024-04-14',
                'estadio_3b_5_numero' => null,
                'estadio_3b_5_fecha' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'adulto_mayor_id' => 10,
                'obesidad' => false,
                'dislipidemia' => true,
                'hipertension_arterial' => true,
                'diabetes_mellitus' => false,
                'erc' => false,
                'osteoartrosis' => false,
                'asma' => false,
                'epoc' => false,
                'itg' => false,
                'sindrome_metabolico' => false,
                'otros' => 'Arritmia cardíaca',
                'visare_numero' => 12351,
                'visare_fecha' => '2024-04-16',
                'estadio_1a_3a_numero' => null,
                'estadio_1a_3a_fecha' => null,
                'estadio_3b_5_numero' => null,
                'estadio_3b_5_fecha' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'adulto_mayor_id' => 11,
                'obesidad' => true,
                'dislipidemia' => true,
                'hipertension_arterial' => true,
                'diabetes_mellitus' => true,
                'erc' => true,
                'osteoartrosis' => true,
                'asma' => false,
                'epoc' => false,
                'itg' => false,
                'sindrome_metabolico' => true,
                'otros' => 'Insuficiencia cardíaca congestiva',
                'visare_numero' => 12352,
                'visare_fecha' => '2024-04-19',
                'estadio_1a_3a_numero' => null,
                'estadio_1a_3a_fecha' => null,
                'estadio_3b_5_numero' => 45678,
                'estadio_3b_5_fecha' => '2024-04-20',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'adulto_mayor_id' => 12,
                'obesidad' => false,
                'dislipidemia' => true,
                'hipertension_arterial' => true,
                'diabetes_mellitus' => false,
                'erc' => false,
                'osteoartrosis' => true,
                'asma' => false,
                'epoc' => true,
                'itg' => false,
                'sindrome_metabolico' => false,
                'otros' => 'Cáncer de próstata en remisión',
                'visare_numero' => 12353,
                'visare_fecha' => '2024-04-21',
                'estadio_1a_3a_numero' => null,
                'estadio_1a_3a_fecha' => null,
                'estadio_3b_5_numero' => null,
                'estadio_3b_5_fecha' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'adulto_mayor_id' => 13,
                'obesidad' => false,
                'dislipidemia' => false,
                'hipertension_arterial' => true,
                'diabetes_mellitus' => false,
                'erc' => false,
                'osteoartrosis' => true,
                'asma' => true,
                'epoc' => false,
                'itg' => false,
                'sindrome_metabolico' => false,
                'otros' => null,
                'visare_numero' => null,
                'visare_fecha' => null,
                'estadio_1a_3a_numero' => null,
                'estadio_1a_3a_fecha' => null,
                'estadio_3b_5_numero' => null,
                'estadio_3b_5_fecha' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'adulto_mayor_id' => 14,
                'obesidad' => false,
                'dislipidemia' => true,
                'hipertension_arterial' => true,
                'diabetes_mellitus' => true,
                'erc' => true,
                'osteoartrosis' => false,
                'asma' => false,
                'epoc' => false,
                'itg' => false,
                'sindrome_metabolico' => true,
                'otros' => 'Neuropatía diabética, Retinopatía diabética',
                'visare_numero' => 12354,
                'visare_fecha' => '2024-04-26',
                'estadio_1a_3a_numero' => 34567,
                'estadio_1a_3a_fecha' => '2024-04-27',
                'estadio_3b_5_numero' => null,
                'estadio_3b_5_fecha' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'adulto_mayor_id' => 15,
                'obesidad' => false,
                'dislipidemia' => false,
                'hipertension_arterial' => false,
                'diabetes_mellitus' => false,
                'erc' => false,
                'osteoartrosis' => false,
                'asma' => false,
                'epoc' => false,
                'itg' => false,
                'sindrome_metabolico' => false,
                'otros' => null,
                'visare_numero' => null,
                'visare_fecha' => null,
                'estadio_1a_3a_numero' => null,
                'estadio_1a_3a_fecha' => null,
                'estadio_3b_5_numero' => null,
                'estadio_3b_5_fecha' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'adulto_mayor_id' => 16,
                'obesidad' => false,
                'dislipidemia' => true,
                'hipertension_arterial' => true,
                'diabetes_mellitus' => false,
                'erc' => false,
                'osteoartrosis' => true,
                'asma' => false,
                'epoc' => false,
                'itg' => false,
                'sindrome_metabolico' => false,
                'otros' => 'Glaucoma',
                'visare_numero' => 12355,
                'visare_fecha' => '2024-05-03',
                'estadio_1a_3a_numero' => null,
                'estadio_1a_3a_fecha' => null,
                'estadio_3b_5_numero' => null,
                'estadio_3b_5_fecha' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'adulto_mayor_id' => 17,
                'obesidad' => true,
                'dislipidemia' => true,
                'hipertension_arterial' => true,
                'diabetes_mellitus' => true,
                'erc' => false,
                'osteoartrosis' => true,
                'asma' => false,
                'epoc' => false,
                'itg' => false,
                'sindrome_metabolico' => true,
                'otros' => 'Demencia vascular leve',
                'visare_numero' => 12356,
                'visare_fecha' => '2024-05-06',
                'estadio_1a_3a_numero' => 78901,
                'estadio_1a_3a_fecha' => '2024-05-07',
                'estadio_3b_5_numero' => null,
                'estadio_3b_5_fecha' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'adulto_mayor_id' => 18,
                'obesidad' => false,
                'dislipidemia' => false,
                'hipertension_arterial' => false,
                'diabetes_mellitus' => false,
                'erc' => false,
                'osteoartrosis' => true,
                'asma' => false,
                'epoc' => false,
                'itg' => false,
                'sindrome_metabolico' => false,
                'otros' => null,
                'visare_numero' => null,
                'visare_fecha' => null,
                'estadio_1a_3a_numero' => null,
                'estadio_1a_3a_fecha' => null,
                'estadio_3b_5_numero' => null,
                'estadio_3b_5_fecha' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'adulto_mayor_id' => 19,
                'obesidad' => false,
                'dislipidemia' => true,
                'hipertension_arterial' => true,
                'diabetes_mellitus' => true,
                'erc' => true,
                'osteoartrosis' => true,
                'asma' => false,
                'epoc' => false,
                'itg' => false,
                'sindrome_metabolico' => true,
                'otros' => 'Fibromialgia, Depresión mayor',
                'visare_numero' => 12357,
                'visare_fecha' => '2024-05-11',
                'estadio_1a_3a_numero' => 23456,
                'estadio_1a_3a_fecha' => '2024-05-12',
                'estadio_3b_5_numero' => null,
                'estadio_3b_5_fecha' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'adulto_mayor_id' => 20,
                'obesidad' => false,
                'dislipidemia' => false,
                'hipertension_arterial' => true,
                'diabetes_mellitus' => false,
                'erc' => false,
                'osteoartrosis' => false,
                'asma' => false,
                'epoc' => false,
                'itg' => false,
                'sindrome_metabolico' => false,
                'otros' => null,
                'visare_numero' => null,
                'visare_fecha' => null,
                'estadio_1a_3a_numero' => null,
                'estadio_1a_3a_fecha' => null,
                'estadio_3b_5_numero' => null,
                'estadio_3b_5_fecha' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ];

        DB::table('enfermedades')->insert($enfermedades);
    }
}