<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class EvaluacionesSeeder extends Seeder
{
    public function run()
    {
        $evaluaciones = [
            [
                'adulto_mayor_id' => 1,
                'talla' => 155,
                'peso_aceptable' => 60.50,
                'peso' => 58.20,
                'presion_arterial' => '140/90',
                'glucosa' => 110.50,
                'hb_glicosilada' => 6.2,
                'imc' => 24.20,
                'perimetro_abdominal' => 85.50,
                'evaluacion_pie_dm' => 'Sin alteraciones',
                'test_morisky_green' => 'cumple',
                'vacuna_influenza' => true,
                'vacuna_neumococo' => true,
                'microalbuminuria' => 15.20,
                'creatinina' => 1.10,
                'tasa_albuminuria_creatinuria' => 18.50,
                'tasa_filtracion_glomerular' => 85.30,
                'control_renal_fecha' => '2024-01-25',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'adulto_mayor_id' => 2,
                'talla' => 168,
                'peso_aceptable' => 70.00,
                'peso' => 85.50,
                'presion_arterial' => '160/95',
                'glucosa' => 180.20,
                'hb_glicosilada' => 8.5,
                'imc' => 30.30,
                'perimetro_abdominal' => 105.00,
                'evaluacion_pie_dm' => 'Neuropatía leve',
                'test_morisky_green' => 'no cumple',
                'vacuna_influenza' => false,
                'vacuna_neumococo' => true,
                'microalbuminuria' => 45.80,
                'creatinina' => 1.80,
                'tasa_albuminuria_creatinuria' => 25.40,
                'tasa_filtracion_glomerular' => 55.20,
                'control_renal_fecha' => '2024-02-20',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'adulto_mayor_id' => 3,
                'talla' => 150,
                'peso_aceptable' => 55.00,
                'peso' => 48.30,
                'presion_arterial' => '120/80',
                'glucosa' => 95.50,
                'hb_glicosilada' => null,
                'imc' => 21.50,
                'perimetro_abdominal' => 75.20,
                'evaluacion_pie_dm' => null,
                'test_morisky_green' => null,
                'vacuna_influenza' => true,
                'vacuna_neumococo' => false,
                'microalbuminuria' => null,
                'creatinina' => 0.90,
                'tasa_albuminuria_creatinuria' => null,
                'tasa_filtracion_glomerular' => 95.50,
                'control_renal_fecha' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'adulto_mayor_id' => 4,
                'talla' => 172,
                'peso_aceptable' => 75.00,
                'peso' => 72.80,
                'presion_arterial' => '135/85',
                'glucosa' => 105.30,
                'hb_glicosilada' => null,
                'imc' => 24.60,
                'perimetro_abdominal' => 88.50,
                'evaluacion_pie_dm' => null,
                'test_morisky_green' => 'cumple',
                'vacuna_influenza' => true,
                'vacuna_neumococo' => true,
                'microalbuminuria' => null,
                'creatinina' => 1.05,
                'tasa_albuminuria_creatinuria' => null,
                'tasa_filtracion_glomerular' => 82.40,
                'control_renal_fecha' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'adulto_mayor_id' => 5,
                'talla' => 160,
                'peso_aceptable' => 65.00,
                'peso' => 63.20,
                'presion_arterial' => '125/80',
                'glucosa' => 88.50,
                'hb_glicosilada' => null,
                'imc' => 24.70,
                'perimetro_abdominal' => 78.50,
                'evaluacion_pie_dm' => null,
                'test_morisky_green' => null,
                'vacuna_influenza' => true,
                'vacuna_neumococo' => true,
                'microalbuminuria' => null,
                'creatinina' => 0.85,
                'tasa_albuminuria_creatinuria' => null,
                'tasa_filtracion_glomerular' => 92.30,
                'control_renal_fecha' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'adulto_mayor_id' => 6,
                'talla' => 165,
                'peso_aceptable' => 68.00,
                'peso' => 52.80,
                'presion_arterial' => '170/100',
                'glucosa' => 220.80,
                'hb_glicosilada' => 9.2,
                'imc' => 19.40,
                'perimetro_abdominal' => 92.00,
                'evaluacion_pie_dm' => 'Neuropatía moderada',
                'test_morisky_green' => 'no cumple',
                'vacuna_influenza' => false,
                'vacuna_neumococo' => false,
                'microalbuminuria' => 85.60,
                'creatinina' => 2.50,
                'tasa_albuminuria_creatinuria' => 34.20,
                'tasa_filtracion_glomerular' => 35.80,
                'control_renal_fecha' => '2024-04-05',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'adulto_mayor_id' => 7,
                'talla' => 152,
                'peso_aceptable' => 58.00,
                'peso' => 78.50,
                'presion_arterial' => '155/92',
                'glucosa' => 125.40,
                'hb_glicosilada' => null,
                'imc' => 34.00,
                'perimetro_abdominal' => 110.50,
                'evaluacion_pie_dm' => null,
                'test_morisky_green' => 'cumple',
                'vacuna_influenza' => true,
                'vacuna_neumococo' => true,
                'microalbuminuria' => null,
                'creatinina' => 1.20,
                'tasa_albuminuria_creatinuria' => null,
                'tasa_filtracion_glomerular' => 78.20,
                'control_renal_fecha' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'adulto_mayor_id' => 8,
                'talla' => 174,
                'peso_aceptable' => 76.00,
                'peso' => 74.20,
                'presion_arterial' => '118/75',
                'glucosa' => 92.30,
                'hb_glicosilada' => null,
                'imc' => 24.50,
                'perimetro_abdominal' => 82.00,
                'evaluacion_pie_dm' => null,
                'test_morisky_green' => null,
                'vacuna_influenza' => true,
                'vacuna_neumococo' => true,
                'microalbuminuria' => null,
                'creatinina' => 0.95,
                'tasa_albuminuria_creatinuria' => null,
                'tasa_filtracion_glomerular' => 88.50,
                'control_renal_fecha' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'adulto_mayor_id' => 9,
                'talla' => 158,
                'peso_aceptable' => 62.00,
                'peso' => 82.30,
                'presion_arterial' => '165/98',
                'glucosa' => 195.70,
                'hb_glicosilada' => 8.8,
                'imc' => 33.00,
                'perimetro_abdominal' => 108.00,
                'evaluacion_pie_dm' => 'Neuropatía leve',
                'test_morisky_green' => 'no cumple',
                'vacuna_influenza' => true,
                'vacuna_neumococo' => false,
                'microalbuminuria' => 52.40,
                'creatinina' => 1.45,
                'tasa_albuminuria_creatinuria' => 36.10,
                'tasa_filtracion_glomerular' => 65.20,
                'control_renal_fecha' => '2024-04-14',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'adulto_mayor_id' => 10,
                'talla' => 170,
                'peso_aceptable' => 72.00,
                'peso' => 69.80,
                'presion_arterial' => '148/88',
                'glucosa' => 108.20,
                'hb_glicosilada' => null,
                'imc' => 24.20,
                'perimetro_abdominal' => 86.50,
                'evaluacion_pie_dm' => null,
                'test_morisky_green' => 'cumple',
                'vacuna_influenza' => true,
                'vacuna_neumococo' => true,
                'microalbuminuria' => null,
                'creatinina' => 1.15,
                'tasa_albuminuria_creatinuria' => null,
                'tasa_filtracion_glomerular' => 80.40,
                'control_renal_fecha' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'adulto_mayor_id' => 11,
                'talla' => 155,
                'peso_aceptable' => 60.00,
                'peso' => 78.20,
                'presion_arterial' => '175/105',
                'glucosa' => 210.50,
                'hb_glicosilada' => 9.5,
                'imc' => 32.60,
                'perimetro_abdominal' => 115.00,
                'evaluacion_pie_dm' => 'Úlcera plantar',
                'test_morisky_green' => 'no cumple',
                'vacuna_influenza' => false,
                'vacuna_neumococo' => false,
                'microalbuminuria' => 95.20,
                'creatinina' => 2.80,
                'tasa_albuminuria_creatinuria' => 42.30,
                'tasa_filtracion_glomerular' => 28.50,
                'control_renal_fecha' => '2024-04-22',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'adulto_mayor_id' => 12,
                'talla' => 173,
                'peso_aceptable' => 75.00,
                'peso' => 71.50,
                'presion_arterial' => '145/90',
                'glucosa' => 98.30,
                'hb_glicosilada' => null,
                'imc' => 23.90,
                'perimetro_abdominal' => 89.50,
                'evaluacion_pie_dm' => null,
                'test_morisky_green' => 'cumple',
                'vacuna_influenza' => true,
                'vacuna_neumococo' => true,
                'microalbuminuria' => null,
                'creatinina' => 1.25,
                'tasa_albuminuria_creatinuria' => null,
                'tasa_filtracion_glomerular' => 75.20,
                'control_renal_fecha' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'adulto_mayor_id' => 13,
                'talla' => 158,
                'peso_aceptable' => 62.00,
                'peso' => 59.80,
                'presion_arterial' => '138/82',
                'glucosa' => 102.40,
                'hb_glicosilada' => null,
                'imc' => 24.00,
                'perimetro_abdominal' => 80.50,
                'evaluacion_pie_dm' => null,
                'test_morisky_green' => 'cumple',
                'vacuna_influenza' => true,
                'vacuna_neumococo' => false,
                'microalbuminuria' => null,
                'creatinina' => 0.95,
                'tasa_albuminuria_creatinuria' => null,
                'tasa_filtracion_glomerular' => 85.30,
                'control_renal_fecha' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'adulto_mayor_id' => 14,
                'talla' => 169,
                'peso_aceptable' => 70.00,
                'peso' => 58.20,
                'presion_arterial' => '180/110',
                'glucosa' => 245.80,
                'hb_glicosilada' => 10.2,
                'imc' => 20.40,
                'perimetro_abdominal' => 85.00,
                'evaluacion_pie_dm' => 'Neuropatía severa',
                'test_morisky_green' => 'no cumple',
                'vacuna_influenza' => false,
                'vacuna_neumococo' => true,
                'microalbuminuria' => 125.60,
                'creatinina' => 3.20,
                'tasa_albuminuria_creatinuria' => 55.40,
                'tasa_filtracion_glomerular' => 22.80,
                'control_renal_fecha' => '2024-04-28',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'adulto_mayor_id' => 15,
                'talla' => 162,
                'peso_aceptable' => 65.00,
                'peso' => 64.20,
                'presion_arterial' => '115/75',
                'glucosa' => 85.50,
                'hb_glicosilada' => null,
                'imc' => 24.50,
                'perimetro_abdominal' => 76.00,
                'evaluacion_pie_dm' => null,
                'test_morisky_green' => null,
                'vacuna_influenza' => true,
                'vacuna_neumococo' => true,
                'microalbuminuria' => null,
                'creatinina' => 0.82,
                'tasa_albuminuria_creatinuria' => null,
                'tasa_filtracion_glomerular' => 95.20,
                'control_renal_fecha' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'adulto_mayor_id' => 16,
                'talla' => 175,
                'peso_aceptable' => 76.00,
                'peso' => 74.80,
                'presion_arterial' => '142/85',
                'glucosa' => 112.30,
                'hb_glicosilada' => null,
                'imc' => 24.40,
                'perimetro_abdominal' => 91.50,
                'evaluacion_pie_dm' => null,
                'test_morisky_green' => 'cumple',
                'vacuna_influenza' => true,
                'vacuna_neumococo' => true,
                'microalbuminuria' => null,
                'creatinina' => 1.08,
                'tasa_albuminuria_creatinuria' => null,
                'tasa_filtracion_glomerular' => 82.60,
                'control_renal_fecha' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'adulto_mayor_id' => 17,
                'talla' => 159,
                'peso_aceptable' => 63.00,
                'peso' => 86.50,
                'presion_arterial' => '168/98',
                'glucosa' => 205.70,
                'hb_glicosilada' => 9.1,
                'imc' => 34.20,
                'perimetro_abdominal' => 112.50,
                'evaluacion_pie_dm' => 'Neuropatía moderada',
                'test_morisky_green' => 'no cumple',
                'vacuna_influenza' => false,
                'vacuna_neumococo' => false,
                'microalbuminuria' => 68.40,
                'creatinina' => 1.65,
                'tasa_albuminuria_creatinuria' => 41.50,
                'tasa_filtracion_glomerular' => 58.30,
                'control_renal_fecha' => '2024-05-08',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'adulto_mayor_id' => 18,
                'talla' => 171,
                'peso_aceptable' => 73.00,
                'peso' => 70.20,
                'presion_arterial' => '122/78',
                'glucosa' => 94.80,
                'hb_glicosilada' => null,
                'imc' => 24.00,
                'perimetro_abdominal' => 84.00,
                'evaluacion_pie_dm' => null,
                'test_morisky_green' => null,
                'vacuna_influenza' => true,
                'vacuna_neumococo' => true,
                'microalbuminuria' => null,
                'creatinina' => 0.98,
                'tasa_albuminuria_creatinuria' => null,
                'tasa_filtracion_glomerular' => 86.70,
                'control_renal_fecha' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'adulto_mayor_id' => 19,
                'talla' => 154,
                'peso_aceptable' => 59.00,
                'peso' => 64.80,
                'presion_arterial' => '158/95',
                'glucosa' => 178.20,
                'hb_glicosilada' => 8.3,
                'imc' => 27.30,
                'perimetro_abdominal' => 98.50,
                'evaluacion_pie_dm' => 'Sin alteraciones',
                'test_morisky_green' => 'cumple',
                'vacuna_influenza' => true,
                'vacuna_neumococo' => false,
                'microalbuminuria' => 38.20,
                'creatinina' => 1.35,
                'tasa_albuminuria_creatinuria' => 28.30,
                'tasa_filtracion_glomerular' => 68.50,
                'control_renal_fecha' => '2024-05-13',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'adulto_mayor_id' => 20,
                'talla' => 168,
                'peso_aceptable' => 70.00,
                'peso' => 68.50,
                'presion_arterial' => '132/80',
                'glucosa' => 96.40,
                'hb_glicosilada' => null,
                'imc' => 24.30,
                'perimetro_abdominal' => 83.50,
                'evaluacion_pie_dm' => null,
                'test_morisky_green' => null,
                'vacuna_influenza' => true,
                'vacuna_neumococo' => true,
                'microalbuminuria' => null,
                'creatinina' => 0.88,
                'tasa_albuminuria_creatinuria' => null,
                'tasa_filtracion_glomerular' => 90.20,
                'control_renal_fecha' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ];

        DB::table('evaluaciones')->insert($evaluaciones);
    }
}