<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class RiesgosSeeder extends Seeder
{
    public function run()
    {
        $riesgos = [
            [
                'adulto_mayor_id' => 1,
                'sobrepeso' => false,
                'sedentarismo' => true,
                'tabaco' => false,
                'alcohol' => false,
                'estres' => true,
                'bajo_peso' => false,
                'perimetro_abdominal_aumentado' => false,
                'hdl_bajo' => true,
                'created_at' => '2024-01-15 10:00:00',
                'updated_at' => '2024-01-15 10:00:00',
            ],
            [
                'adulto_mayor_id' => 2,
                'sobrepeso' => true,
                'sedentarismo' => true,
                'tabaco' => true,
                'alcohol' => false,
                'estres' => true,
                'bajo_peso' => false,
                'perimetro_abdominal_aumentado' => true,
                'hdl_bajo' => true,
                'created_at' => '2024-02-10 09:15:00',
                'updated_at' => '2024-02-10 09:15:00',
            ],
            [
                'adulto_mayor_id' => 3,
                'sobrepeso' => false,
                'sedentarismo' => false,
                'tabaco' => false,
                'alcohol' => false,
                'estres' => false,
                'bajo_peso' => true,
                'perimetro_abdominal_aumentado' => false,
                'hdl_bajo' => false,
                'created_at' => '2024-03-04 08:20:00',
                'updated_at' => '2024-03-04 08:20:00',
            ],
            [
                'adulto_mayor_id' => 4,
                'sobrepeso' => false,
                'sedentarismo' => true,
                'tabaco' => false,
                'alcohol' => true,
                'estres' => false,
                'bajo_peso' => false,
                'perimetro_abdominal_aumentado' => false,
                'hdl_bajo' => true,
                'created_at' => '2024-03-15 15:10:00',
                'updated_at' => '2024-03-15 15:10:00',
            ],
            [
                'adulto_mayor_id' => 5,
                'sobrepeso' => false,
                'sedentarismo' => false,
                'tabaco' => false,
                'alcohol' => false,
                'estres' => false,
                'bajo_peso' => false,
                'perimetro_abdominal_aumentado' => false,
                'hdl_bajo' => false,
                'created_at' => '2024-03-25 13:30:00',
                'updated_at' => '2024-03-25 13:30:00',
            ],
            [
                'adulto_mayor_id' => 6,
                'sobrepeso' => false,
                'sedentarismo' => true,
                'tabaco' => true,
                'alcohol' => true,
                'estres' => true,
                'bajo_peso' => true,
                'perimetro_abdominal_aumentado' => false,
                'hdl_bajo' => true,
                'created_at' => '2024-04-01 09:00:00',
                'updated_at' => '2024-04-01 09:00:00',
            ],
            [
                'adulto_mayor_id' => 7,
                'sobrepeso' => true,
                'sedentarismo' => true,
                'tabaco' => false,
                'alcohol' => false,
                'estres' => true,
                'bajo_peso' => false,
                'perimetro_abdominal_aumentado' => true,
                'hdl_bajo' => true,
                'created_at' => '2024-04-05 11:30:00',
                'updated_at' => '2024-04-05 11:30:00',
            ],
            [
                'adulto_mayor_id' => 8,
                'sobrepeso' => false,
                'sedentarismo' => false,
                'tabaco' => false,
                'alcohol' => false,
                'estres' => false,
                'bajo_peso' => false,
                'perimetro_abdominal_aumentado' => false,
                'hdl_bajo' => false,
                'created_at' => '2024-04-10 16:45:00',
                'updated_at' => '2024-04-10 16:45:00',
            ],
            [
                'adulto_mayor_id' => 9,
                'sobrepeso' => true,
                'sedentarismo' => true,
                'tabaco' => false,
                'alcohol' => false,
                'estres' => true,
                'bajo_peso' => false,
                'perimetro_abdominal_aumentado' => true,
                'hdl_bajo' => true,
                'created_at' => '2024-04-12 08:30:00',
                'updated_at' => '2024-04-12 08:30:00',
            ],
            [
                'adulto_mayor_id' => 10,
                'sobrepeso' => false,
                'sedentarismo' => true,
                'tabaco' => false,
                'alcohol' => true,
                'estres' => false,
                'bajo_peso' => false,
                'perimetro_abdominal_aumentado' => false,
                'hdl_bajo' => true,
                'created_at' => '2024-04-15 15:40:00',
                'updated_at' => '2024-04-15 15:40:00',
            ],
            [
                'adulto_mayor_id' => 11,
                'sobrepeso' => true,
                'sedentarismo' => true,
                'tabaco' => false,
                'alcohol' => false,
                'estres' => true,
                'bajo_peso' => false,
                'perimetro_abdominal_aumentado' => true,
                'hdl_bajo' => true,
                'created_at' => '2024-04-18 09:50:00',
                'updated_at' => '2024-04-18 09:50:00',
            ],
            [
                'adulto_mayor_id' => 12,
                'sobrepeso' => false,
                'sedentarismo' => true,
                'tabaco' => true,
                'alcohol' => true,
                'estres' => false,
                'bajo_peso' => false,
                'perimetro_abdominal_aumentado' => false,
                'hdl_bajo' => true,
                'created_at' => '2024-04-20 10:40:00',
                'updated_at' => '2024-04-20 10:40:00',
            ],
            [
                'adulto_mayor_id' => 13,
                'sobrepeso' => false,
                'sedentarismo' => false,
                'tabaco' => false,
                'alcohol' => false,
                'estres' => true,
                'bajo_peso' => false,
                'perimetro_abdominal_aumentado' => false,
                'hdl_bajo' => false,
                'created_at' => '2024-04-22 14:55:00',
                'updated_at' => '2024-04-22 14:55:00',
            ],
            [
                'adulto_mayor_id' => 14,
                'sobrepeso' => false,
                'sedentarismo' => true,
                'tabaco' => false,
                'alcohol' => false,
                'estres' => true,
                'bajo_peso' => true,
                'perimetro_abdominal_aumentado' => false,
                'hdl_bajo' => true,
                'created_at' => '2024-04-25 11:10:00',
                'updated_at' => '2024-04-25 11:10:00',
            ],
            [
                'adulto_mayor_id' => 15,
                'sobrepeso' => false,
                'sedentarismo' => false,
                'tabaco' => false,
                'alcohol' => false,
                'estres' => false,
                'bajo_peso' => false,
                'perimetro_abdominal_aumentado' => false,
                'hdl_bajo' => false,
                'created_at' => '2024-05-09 16:20:00',
                'updated_at' => '2024-05-09 16:20:00',
            ],
            [
                'adulto_mayor_id' => 16,
                'sobrepeso' => false,
                'sedentarismo' => true,
                'tabaco' => false,
                'alcohol' => false,
                'estres' => false,
                'bajo_peso' => false,
                'perimetro_abdominal_aumentado' => false,
                'hdl_bajo' => true,
                'created_at' => '2024-05-03 16:20:00',
                'updated_at' => '2024-05-03 16:20:00',
            ],
            [
                'adulto_mayor_id' => 17,
                'sobrepeso' => true,
                'sedentarismo' => true,
                'tabaco' => false,
                'alcohol' => false,
                'estres' => true,
                'bajo_peso' => false,
                'perimetro_abdominal_aumentado' => true,
                'hdl_bajo' => true,
                'created_at' => '2024-05-05 16:20:00',
                'updated_at' => '2024-05-05 16:20:00',
            ],
            [
                'adulto_mayor_id' => 18,
                'sobrepeso' => false,
                'sedentarismo' => false,
                'tabaco' => false,
                'alcohol' => false,
                'estres' => false,
                'bajo_peso' => false,
                'perimetro_abdominal_aumentado' => false,
                'hdl_bajo' => false,
                'created_at' => '2025-05-03 16:20:00',
                'updated_at' => '2025-05-03 16:20:00',
            ],
            [
                'adulto_mayor_id' => 19,
                'sobrepeso' => false,
                'sedentarismo' => true,
                'tabaco' => false,
                'alcohol' => false,
                'estres' => true,
                'bajo_peso' => false,
                'perimetro_abdominal_aumentado' => false,
                'hdl_bajo' => true,
                'created_at' => '2025-08-10 10:25:00',
                'updated_at' => '2025-08-10 10:25:00',
            ],
            [
                'adulto_mayor_id' => 20,
                'sobrepeso' => false,
                'sedentarismo' => false,
                'tabaco' => false,
                'alcohol' => false,
                'estres' => false,
                'bajo_peso' => false,
                'perimetro_abdominal_aumentado' => false,
                'hdl_bajo' => false,
                'created_at' => '2025-09-12 11:05:00',
                'updated_at' => '2025-09-12 11:05:00',
            ],
        ];

        DB::table('riesgos')->insert($riesgos);
    }
}