<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class RiesgosSeeder extends Seeder
{
    public function run()
    {
        $riesgos = [
            [
                'adulto_mayor_id' => 1,
                'sobrepeso' => false,
                'sedentarismo' => true,
                'tabaco' => false,
                'alcohol' => false,
                'estres' => true,
                'bajo_peso' => false,
                'perimetro_abdominal_aumentado' => false,
                'hdl_bajo' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'adulto_mayor_id' => 2,
                'sobrepeso' => true,
                'sedentarismo' => true,
                'tabaco' => true,
                'alcohol' => false,
                'estres' => true,
                'bajo_peso' => false,
                'perimetro_abdominal_aumentado' => true,
                'hdl_bajo' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'adulto_mayor_id' => 3,
                'sobrepeso' => false,
                'sedentarismo' => false,
                'tabaco' => false,
                'alcohol' => false,
                'estres' => false,
                'bajo_peso' => true,
                'perimetro_abdominal_aumentado' => false,
                'hdl_bajo' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'adulto_mayor_id' => 4,
                'sobrepeso' => false,
                'sedentarismo' => true,
                'tabaco' => false,
                'alcohol' => true,
                'estres' => false,
                'bajo_peso' => false,
                'perimetro_abdominal_aumentado' => false,
                'hdl_bajo' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'adulto_mayor_id' => 5,
                'sobrepeso' => false,
                'sedentarismo' => false,
                'tabaco' => false,
                'alcohol' => false,
                'estres' => false,
                'bajo_peso' => false,
                'perimetro_abdominal_aumentado' => false,
                'hdl_bajo' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'adulto_mayor_id' => 6,
                'sobrepeso' => false,
                'sedentarismo' => true,
                'tabaco' => true,
                'alcohol' => true,
                'estres' => true,
                'bajo_peso' => true,
                'perimetro_abdominal_aumentado' => false,
                'hdl_bajo' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'adulto_mayor_id' => 7,
                'sobrepeso' => true,
                'sedentarismo' => true,
                'tabaco' => false,
                'alcohol' => false,
                'estres' => true,
                'bajo_peso' => false,
                'perimetro_abdominal_aumentado' => true,
                'hdl_bajo' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'adulto_mayor_id' => 8,
                'sobrepeso' => false,
                'sedentarismo' => false,
                'tabaco' => false,
                'alcohol' => false,
                'estres' => false,
                'bajo_peso' => false,
                'perimetro_abdominal_aumentado' => false,
                'hdl_bajo' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'adulto_mayor_id' => 9,
                'sobrepeso' => true,
                'sedentarismo' => true,
                'tabaco' => false,
                'alcohol' => false,
                'estres' => true,
                'bajo_peso' => false,
                'perimetro_abdominal_aumentado' => true,
                'hdl_bajo' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'adulto_mayor_id' => 10,
                'sobrepeso' => false,
                'sedentarismo' => true,
                'tabaco' => false,
                'alcohol' => true,
                'estres' => false,
                'bajo_peso' => false,
                'perimetro_abdominal_aumentado' => false,
                'hdl_bajo' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'adulto_mayor_id' => 11,
                'sobrepeso' => true,
                'sedentarismo' => true,
                'tabaco' => false,
                'alcohol' => false,
                'estres' => true,
                'bajo_peso' => false,
                'perimetro_abdominal_aumentado' => true,
                'hdl_bajo' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'adulto_mayor_id' => 12,
                'sobrepeso' => false,
                'sedentarismo' => true,
                'tabaco' => true,
                'alcohol' => true,
                'estres' => false,
                'bajo_peso' => false,
                'perimetro_abdominal_aumentado' => false,
                'hdl_bajo' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'adulto_mayor_id' => 13,
                'sobrepeso' => false,
                'sedentarismo' => false,
                'tabaco' => false,
                'alcohol' => false,
                'estres' => true,
                'bajo_peso' => false,
                'perimetro_abdominal_aumentado' => false,
                'hdl_bajo' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'adulto_mayor_id' => 14,
                'sobrepeso' => false,
                'sedentarismo' => true,
                'tabaco' => false,
                'alcohol' => false,
                'estres' => true,
                'bajo_peso' => true,
                'perimetro_abdominal_aumentado' => false,
                'hdl_bajo' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'adulto_mayor_id' => 15,
                'sobrepeso' => false,
                'sedentarismo' => false,
                'tabaco' => false,
                'alcohol' => false,
                'estres' => false,
                'bajo_peso' => false,
                'perimetro_abdominal_aumentado' => false,
                'hdl_bajo' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'adulto_mayor_id' => 16,
                'sobrepeso' => false,
                'sedentarismo' => true,
                'tabaco' => false,
                'alcohol' => false,
                'estres' => false,
                'bajo_peso' => false,
                'perimetro_abdominal_aumentado' => false,
                'hdl_bajo' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'adulto_mayor_id' => 17,
                'sobrepeso' => true,
                'sedentarismo' => true,
                'tabaco' => false,
                'alcohol' => false,
                'estres' => true,
                'bajo_peso' => false,
                'perimetro_abdominal_aumentado' => true,
                'hdl_bajo' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'adulto_mayor_id' => 18,
                'sobrepeso' => false,
                'sedentarismo' => false,
                'tabaco' => false,
                'alcohol' => false,
                'estres' => false,
                'bajo_peso' => false,
                'perimetro_abdominal_aumentado' => false,
                'hdl_bajo' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'adulto_mayor_id' => 19,
                'sobrepeso' => false,
                'sedentarismo' => true,
                'tabaco' => false,
                'alcohol' => false,
                'estres' => true,
                'bajo_peso' => false,
                'perimetro_abdominal_aumentado' => false,
                'hdl_bajo' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'adulto_mayor_id' => 20,
                'sobrepeso' => false,
                'sedentarismo' => false,
                'tabaco' => false,
                'alcohol' => false,
                'estres' => false,
                'bajo_peso' => false,
                'perimetro_abdominal_aumentado' => false,
                'hdl_bajo' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ];

        DB::table('riesgos')->insert($riesgos);
    }
}