<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ValoracionesSeeder extends Seeder
{
    public function run()
    {
        $valoraciones = [
            [
                'adulto_mayor_id' => 1,
                'autovalente' => true,
                'test_barber' => 'Sin deterioro',
                'test_barthel' => '85 puntos',
                'fragil' => false,
                'test_lawton_brody' => '6 puntos',
                'test_katz' => 'Independiente',
                'fecha_enfermeria' => '2024-01-15',
                'fecha_medicina' => '2024-01-15',
                'fecha_nutricion' => '2024-01-20',
                'fecha_psicologia' => null,
                'fecha_servicio_social' => null,
                'fecha_visita_domiciliaria' => '2024-01-25',
                'created_at' => '2024-01-20 10:00:00',
                'updated_at' => '2024-01-20 10:00:00',
            ],
            [
                'adulto_mayor_id' => 2,
                'autovalente' => false,
                'test_barber' => 'Deterioro moderado',
                'test_barthel' => '60 puntos',
                'fragil' => true,
                'test_lawton_brody' => '3 puntos',
                'test_katz' => 'Dependiente parcial',
                'fecha_enfermeria' => '2024-02-10',
                'fecha_medicina' => '2024-02-10',
                'fecha_nutricion' => '2024-02-15',
                'fecha_psicologia' => '2024-02-20',
                'fecha_servicio_social' => '2024-02-25',
                'fecha_visita_domiciliaria' => '2024-03-01',
                'created_at' => '2024-03-01 10:00:00',
                'updated_at' => '2024-03-01 10:00:00',
            ],
            [
                'adulto_mayor_id' => 3,
                'autovalente' => true,
                'test_barber' => 'Sin deterioro',
                'test_barthel' => '95 puntos',
                'fragil' => false,
                'test_lawton_brody' => '7 puntos',
                'test_katz' => 'Independiente',
                'fecha_enfermeria' => '2024-03-05',
                'fecha_medicina' => null,
                'fecha_nutricion' => '2024-03-10',
                'fecha_psicologia' => null,
                'fecha_servicio_social' => null,
                'fecha_visita_domiciliaria' => null,
                'created_at' => '2024-03-10 10:00:00',
                'updated_at' => '2024-03-10 10:00:00',
            ],
            [
                'adulto_mayor_id' => 4,
                'autovalente' => true,
                'test_barber' => 'Sin deterioro',
                'test_barthel' => '90 puntos',
                'fragil' => false,
                'test_lawton_brody' => '6 puntos',
                'test_katz' => 'Independiente',
                'fecha_enfermeria' => '2024-03-15',
                'fecha_medicina' => '2024-03-15',
                'fecha_nutricion' => null,
                'fecha_psicologia' => null,
                'fecha_servicio_social' => null,
                'fecha_visita_domiciliaria' => null,
                'created_at' => '2024-03-15 10:00:00',
                'updated_at' => '2024-03-15 10:00:00',
            ],
            [
                'adulto_mayor_id' => 5,
                'autovalente' => true,
                'test_barber' => 'Sin deterioro',
                'test_barthel' => '100 puntos',
                'fragil' => false,
                'test_lawton_brody' => '8 puntos',
                'test_katz' => 'Independiente',
                'fecha_enfermeria' => '2024-03-20',
                'fecha_medicina' => null,
                'fecha_nutricion' => null,
                'fecha_psicologia' => null,
                'fecha_servicio_social' => null,
                'fecha_visita_domiciliaria' => null,
                'created_at' => '2024-03-20 10:00:00',
                'updated_at' => '2024-03-20 10:00:00',
            ],
            [
                'adulto_mayor_id' => 6,
                'autovalente' => false,
                'test_barber' => 'Deterioro severo',
                'test_barthel' => '40 puntos',
                'fragil' => true,
                'test_lawton_brody' => '2 puntos',
                'test_katz' => 'Dependiente total',
                'fecha_enfermeria' => '2024-04-01',
                'fecha_medicina' => '2024-04-01',
                'fecha_nutricion' => '2024-04-03',
                'fecha_psicologia' => '2024-04-05',
                'fecha_servicio_social' => '2024-04-08',
                'fecha_visita_domiciliaria' => '2024-04-10',
                'created_at' => '2024-04-10 10:00:00',
                'updated_at' => '2024-04-10 10:00:00',
            ],
            [
                'adulto_mayor_id' => 7,
                'autovalente' => false,
                'test_barber' => 'Deterioro leve',
                'test_barthel' => '75 puntos',
                'fragil' => false,
                'test_lawton_brody' => '5 puntos',
                'test_katz' => 'Dependiente parcial',
                'fecha_enfermeria' => '2024-04-05',
                'fecha_medicina' => '2024-04-05',
                'fecha_nutricion' => '2024-04-08',
                'fecha_psicologia' => null,
                'fecha_servicio_social' => null,
                'fecha_visita_domiciliaria' => '2024-04-12',
                'created_at' => '2024-04-12 10:00:00',
                'updated_at' => '2024-04-12 10:00:00',
            ],
            [
                'adulto_mayor_id' => 8,
                'autovalente' => true,
                'test_barber' => 'Sin deterioro',
                'test_barthel' => '95 puntos',
                'fragil' => false,
                'test_lawton_brody' => '7 puntos',
                'test_katz' => 'Independiente',
                'fecha_enfermeria' => '2024-04-10',
                'fecha_medicina' => null,
                'fecha_nutricion' => null,
                'fecha_psicologia' => null,
                'fecha_servicio_social' => null,
                'fecha_visita_domiciliaria' => null,
                'created_at' => '2024-04-20 10:00:00',
                'updated_at' => '2024-04-20 10:00:00',
            ],
            [
                'adulto_mayor_id' => 9,
                'autovalente' => false,
                'test_barber' => 'Deterioro moderado',
                'test_barthel' => '65 puntos',
                'fragil' => true,
                'test_lawton_brody' => '4 puntos',
                'test_katz' => 'Dependiente parcial',
                'fecha_enfermeria' => '2024-04-12',
                'fecha_medicina' => '2024-04-12',
                'fecha_nutricion' => '2024-04-15',
                'fecha_psicologia' => '2024-04-18',
                'fecha_servicio_social' => '2024-04-20',
                'fecha_visita_domiciliaria' => '2024-04-25',
                'created_at' => '2024-04-25 10:00:00',
                'updated_at' => '2024-04-25 10:00:00',
            ],
            [
                'adulto_mayor_id' => 10,
                'autovalente' => true,
                'test_barber' => 'Sin deterioro',
                'test_barthel' => '88 puntos',
                'fragil' => false,
                'test_lawton_brody' => '6 puntos',
                'test_katz' => 'Independiente',
                'fecha_enfermeria' => '2024-04-15',
                'fecha_medicina' => '2024-04-15',
                'fecha_nutricion' => null,
                'fecha_psicologia' => null,
                'fecha_servicio_social' => null,
                'fecha_visita_domiciliaria' => null,
                'created_at' => '2024-04-27 10:00:00',
                'updated_at' => '2024-04-27 10:00:00',
            ],
            [
                'adulto_mayor_id' => 11,
                'autovalente' => false,
                'test_barber' => 'Deterioro severo',
                'test_barthel' => '35 puntos',
                'fragil' => true,
                'test_lawton_brody' => '1 punto',
                'test_katz' => 'Dependiente total',
                'fecha_enfermeria' => '2024-04-18',
                'fecha_medicina' => '2024-04-18',
                'fecha_nutricion' => '2024-04-20',
                'fecha_psicologia' => '2024-04-22',
                'fecha_servicio_social' => '2024-04-25',
                'fecha_visita_domiciliaria' => '2024-04-28',
                'created_at' => '2024-04-28 10:00:00',
                'updated_at' => '2024-04-28 10:00:00',
            ],
            [
                'adulto_mayor_id' => 12,
                'autovalente' => true,
                'test_barber' => 'Sin deterioro',
                'test_barthel' => '82 puntos',
                'fragil' => false,
                'test_lawton_brody' => '5 puntos',
                'test_katz' => 'Independiente',
                'fecha_enfermeria' => '2024-04-20',
                'fecha_medicina' => '2024-04-20',
                'fecha_nutricion' => null,
                'fecha_psicologia' => null,
                'fecha_servicio_social' => null,
                'fecha_visita_domiciliaria' => null,
                'created_at' => '2024-04-29 10:00:00',
                'updated_at' => '2024-04-29 10:00:00',
            ],
            [
                'adulto_mayor_id' => 13,
                'autovalente' => true,
                'test_barber' => 'Sin deterioro',
                'test_barthel' => '92 puntos',
                'fragil' => false,
                'test_lawton_brody' => '7 puntos',
                'test_katz' => 'Independiente',
                'fecha_enfermeria' => '2024-04-22',
                'fecha_medicina' => null,
                'fecha_nutricion' => null,
                'fecha_psicologia' => null,
                'fecha_servicio_social' => null,
                'fecha_visita_domiciliaria' => null,
                'created_at' => '2024-04-29 10:00:00',
                'updated_at' => '2024-04-29 10:00:00',
            ],
            [
                'adulto_mayor_id' => 14,
                'autovalente' => false,
                'test_barber' => 'Deterioro severo',
                'test_barthel' => '45 puntos',
                'fragil' => true,
                'test_lawton_brody' => '2 puntos',
                'test_katz' => 'Dependiente total',
                'fecha_enfermeria' => '2024-04-25',
                'fecha_medicina' => '2024-04-25',
                'fecha_nutricion' => '2024-04-28',
                'fecha_psicologia' => '2024-05-02',
                'fecha_servicio_social' => '2024-05-05',
                'fecha_visita_domiciliaria' => '2024-05-08',
                'created_at' => '2024-05-08 10:00:00',
                'updated_at' => '2024-05-08 10:00:00',
            ],
            [
                'adulto_mayor_id' => 15,
                'autovalente' => true,
                'test_barber' => 'Sin deterioro',
                'test_barthel' => '100 puntos',
                'fragil' => false,
                'test_lawton_brody' => '8 puntos',
                'test_katz' => 'Independiente',
                'fecha_enfermeria' => '2024-04-28',
                'fecha_medicina' => null,
                'fecha_nutricion' => null,
                'fecha_psicologia' => null,
                'fecha_servicio_social' => null,
                'fecha_visita_domiciliaria' => null,
                'created_at' => '2024-05-09 10:00:00',
                'updated_at' => '2024-05-09 10:00:00',
            ],
            [
                'adulto_mayor_id' => 16,
                'autovalente' => true,
                'test_barber' => 'Sin deterioro',
                'test_barthel' => '85 puntos',
                'fragil' => false,
                'test_lawton_brody' => '6 puntos',
                'test_katz' => 'Independiente',
                'fecha_enfermeria' => '2024-05-02',
                'fecha_medicina' => '2024-05-02',
                'fecha_nutricion' => null,
                'fecha_psicologia' => null,
                'fecha_servicio_social' => null,
                'fecha_visita_domiciliaria' => null,
                'created_at' => '2024-05-12 10:00:00',
                'updated_at' => '2024-05-12 10:00:00',
            ],
            [
                'adulto_mayor_id' => 17,
                'autovalente' => false,
                'test_barber' => 'Deterioro moderado',
                'test_barthel' => '58 puntos',
                'fragil' => true,
                'test_lawton_brody' => '3 puntos',
                'test_katz' => 'Dependiente parcial',
                'fecha_enfermeria' => '2024-05-05',
                'fecha_medicina' => '2024-05-05',
                'fecha_nutricion' => '2024-05-08',
                'fecha_psicologia' => '2024-05-12',
                'fecha_servicio_social' => '2024-05-15',
                'fecha_visita_domiciliaria' => '2024-05-18',
                'created_at' => '2024-05-18 10:00:00',
                'updated_at' => '2024-05-18 10:00:00',
            ],
            [
                'adulto_mayor_id' => 18,
                'autovalente' => true,
                'test_barber' => 'Sin deterioro',
                'test_barthel' => '95 puntos',
                'fragil' => false,
                'test_lawton_brody' => '7 puntos',
                'test_katz' => 'Independiente',
                'fecha_enfermeria' => '2025-05-03',
                'fecha_medicina' => null,
                'fecha_nutricion' => null,
                'fecha_psicologia' => null,
                'fecha_servicio_social' => null,
                'fecha_visita_domiciliaria' => null,
                'created_at' => '2025-05-03 10:00:00',
                'updated_at' => '2025-05-03 10:00:00',
            ],
            [
                'adulto_mayor_id' => 19,
                'autovalente' => false,
                'test_barber' => 'Deterioro moderado',
                'test_barthel' => '62 puntos',
                'fragil' => true,
                'test_lawton_brody' => '4 puntos',
                'test_katz' => 'Dependiente parcial',
                'fecha_enfermeria' => '2025-05-10',
                'fecha_medicina' => '2025-05-10',
                'fecha_nutricion' => '2025-05-13',
                'fecha_psicologia' => '2025-05-16',
                'fecha_servicio_social' => '2025-07-20',
                'fecha_visita_domiciliaria' => '2025-08-10',
                'created_at' => '2025-05-10 10:25:00',
                'updated_at' => '2025-05-10 10:25:00',
            ],
            [
                'adulto_mayor_id' => 20,
                'autovalente' => true,
                'test_barber' => 'Sin deterioro',
                'test_barthel' => '90 puntos',
                'fragil' => false,
                'test_lawton_brody' => '6 puntos',
                'test_katz' => 'Independiente',
                'fecha_enfermeria' => '2025-09-12',
                'fecha_medicina' => '2025-09-12',
                'fecha_nutricion' => null,
                'fecha_psicologia' => null,
                'fecha_servicio_social' => null,
                'fecha_visita_domiciliaria' => null,
                'created_at' => '2025-09-12 11:05:00',
                'updated_at' => '2025-09-12 11:05:00',
            ],
        ];

        DB::table('valoraciones')->insert($valoraciones);
    }
}