<?php

namespace Database\Factories;

use App\Models\AdultoMayor;
use App\Models\User;
use Illuminate\Database\Eloquent\Factories\Factory;

class AdultoMayorFactory extends Factory
{
    protected $model = AdultoMayor::class;

    public function definition(): array
    {
        $apellidos = [
            'García',
            'Rodríguez',
            'González',
            'Fernández',
            'López',
            'Martínez',
            'Sánchez',
            'Pérez',
            'Gómez',
            'Martín',
            'Jiménez',
            'Ruiz',
            'Hernández',
            'Díaz',
            'Moreno',
            'Álvarez',
            'Muñoz',
            'Romero',
            'Alonso',
            'Gutiérrez',
            'Navarro',
            'Torres',
            'Domínguez',
            'Vázquez',
            'Ramos',
            'Gil',
            'Ramírez',
            'Serrano',
            'Blanco',
            'Suárez',
            'Molina',
            'Castro',
            'Ortiz',
            'Rubio',
            'Marín',
            'Sanz',
            'Iglesias',
            'Medina',
            'Garrido',
            'Cortés',
            'Castillo'
        ];

        $nombresMasculinos = [
            'José',
            'Antonio',
            'Juan',
            'Manuel',
            'Francisco',
            'Pedro',
            'Luis',
            'Miguel',
            'Ángel',
            'Carlos',
            'Ramón',
            'Vicente',
            'Rafael',
            'Fernando',
            'Enrique',
            'Alberto',
            'Roberto',
            'Ricardo',
            'Andrés',
            'Jorge',
            'Jesús',
            'Javier',
            'Raúl',
            'Sergio',
            'Arturo',
            'Héctor',
            'Julio',
            'Alejandro',
            'Gustavo',
            'Víctor',
            'Mario',
            'Óscar',
            'César',
            'Alfredo',
            'Ernesto',
            'Guillermo',
            'Tomás',
            'Martín',
            'Ignacio',
            'Felipe',
        ];

        $nombresFemeninos = [
            'María',
            'Rosa',
            'Carmen',
            'Juana',
            'Ana',
            'Isabel',
            'Teresa',
            'Dolores',
            'Francisca',
            'Josefa',
            'Concepción',
            'Pilar',
            'Mercedes',
            'Antonia',
            'Cristina',
            'Elena',
            'Julia',
            'Patricia',
            'Beatriz',
            'Silvia',
            'Margarita',
            'Gloria',
            'Lucía',
            'Victoria',
            'Raquel',
            'Susana',
            'Mónica',
            'Yolanda',
            'Angela',
            'Laura',
            'Alicia',
            'Graciela',
            'Catalina',
            'Cecilia',
            'Diana',
            'Martha',
            'Gladys',
            'Lidia',
            'Nélida',
            'Estela',
        ];

        // Códigos IPRESS disponibles
        $ipressCodes = [
            '00009926',
            '00009921',
            '00009925',
            '00009204',
            '00009920',
            '00009059',
            '00009055',
            '00009054',
            '00009053',
            '00009924',
            '00009047',
            '00009922',
            '000010013',
            '00009203',
            '00009202',
            '00009060',
            '00009923',
            '00009201',
            '00009057',
            '000033542',
            '000036306'
        ];

        // Mapeo de IPRESS a ubicación
        $ipressLocation = [
            '00009926' => ['distrito' => 'Piscobamba', 'provincia' => 'Mariscal Luzuriaga'],
            '00009921' => ['distrito' => 'Nepeña', 'provincia' => 'Santa'],
            '00009925' => ['distrito' => 'Pallasca', 'provincia' => 'Pallasca'],
            '00009204' => ['distrito' => 'Huari', 'provincia' => 'Huari'],
            '00009920' => ['distrito' => 'Caraz', 'provincia' => 'Huaylas'],
            '00009059' => ['distrito' => 'Huarmey', 'provincia' => 'Huarmey'],
            '00009055' => ['distrito' => 'Coishco', 'provincia' => 'Santa'],
            '00009054' => ['distrito' => 'Nuevo Chimbote', 'provincia' => 'Santa'],
            '00009053' => ['distrito' => 'Independencia', 'provincia' => 'Huaraz'],
            '00009924' => ['distrito' => 'Cabana', 'provincia' => 'Pallasca'],
            '00009047' => ['distrito' => 'Chimbote', 'provincia' => 'Santa'],
            '00009922' => ['distrito' => 'Pomabamba', 'provincia' => 'Pomabamba'],
            '000010013' => ['distrito' => 'Chimbote', 'provincia' => 'Santa'],
            '00009203' => ['distrito' => 'Sihuas', 'provincia' => 'Sihuas'],
            '00009202' => ['distrito' => 'Pampas', 'provincia' => 'Pallasca'],
            '00009060' => ['distrito' => 'Carhuaz', 'provincia' => 'Carhuaz'],
            '00009923' => ['distrito' => 'Yungay', 'provincia' => 'Yungay'],
            '00009201' => ['distrito' => 'Conchucos', 'provincia' => 'Pallasca'],
            '00009057' => ['distrito' => 'Casma', 'provincia' => 'Casma'],
            '000033542' => ['distrito' => 'Nepeña', 'provincia' => 'Santa'],
            '000036306' => ['distrito' => 'Conchucos', 'provincia' => 'Pallasca'],
        ];

        // Calles por ubicación
        $callesPorUbicacion = [
            'Piscobamba' => [
                'Av. República de Suiza',
                'Calle San Andres',
                'Calle Santo Toribio',
                'Jr. Capac Yupanqui',
                'Jr. Convento',
                'Jr. Guaman Poma de Ayala',
                'Jr. Huancayo',
                'Jr. Manco Inca',
                'Jr. Manuel Arturo Odria',
                'Jr. Marcelino Orcaña',
                'Jr. Salas',
                'Jr. Tupac Yupanqui'
            ],
            'Pallasca' => [
                'Jr. Marañon',
                'Jr. San Martin',
                'Jr. Soledad',
                'Jr. Grau',
                'Jr. Amazonas',
                'Jr. Huallaga',
                'Jr. Comercio',
                'Jr. Trujillo'
            ],
            'Nepeña' => [
                'Avenida 28 de Julio',
                'Avenida El Comercio',
                'Avenida Iquitos',
                'Avenida Juan Velasco Alvarado',
                'Avenida Plaza de Armas',
                'Avenida Progreso',
                'Avenida Santa Rosa',
                'Calle Ancash',
                'Calle Augusto B. Leguía',
                'Jr. Ladislao Espinar',
                'Calle Hipolito Unanue',
                'Av. Solivin',
                'Calle Guillermo Campos',
                'Av. Daniel Alcides Carrion',
                'Calle Pedro Ruiz Gallo',
                'Calle Tupac Amaru'
            ],
            'Huari' => [
                'Avenida 14 de Junio',
                'Avenida Circunvalación',
                'Avenida San Bartolomé',
                'Jirón 24 de Agosto',
                'Jirón Adán Tello',
                'Jirón Ancash',
                'Jirón Libertad',
                'Jirón Leoncio Prado'
            ],
            'Caraz' => [
                'Av. Meza Arizona',
                'Av. Boulevard Llullan',
                'Av. Las Gardenias',
                'Av. Los Meandros',
                'Av. Palmira',
                'Av. Tumshukayko',
                'Jr. Antonio Raimondi',
                'Jr. Arequipa',
                'Jr. Bolognesi',
                'Jr. Camino Real',
                'Jr. Grau',
                'Jr. Jorge Chavez',
                'Jr. José Gálvez',
                'Jr. Kankas',
                'Jr. La Mar'
            ],
            'Huarmey' => [
                'Av. Aija',
                'Av. Alberto Reyes',
                'Av. Alfonso Ugarte',
                'Av. Garcilaso de la Vega',
                'Av. Olivar',
                'Av. Puerto Grande',
                'Calle Cesar Vallejo',
                'Calle Ernesto Reyna',
                'Calle Francisco Bolognesi',
                'Calle Gonzales Prada',
                'Calle Jose Santos Cocano',
                'Calle Manuel Scorza',
                'Calle María Graña',
                'Calle MIguel Grau'
            ],
            'Coishco' => [
                'Avenida Villa del Mar',
                'Calle Alfonso Ugarte',
                'Calle Bienaventurados',
                'Calle Buenos Aires',
                'Calle Coishco',
                'Calle D. Alcides Carrión',
                'Calle Huascar',
                'Jirón 28 de Julio',
                'Jirón Amazonas',
                'Jirón Ancash',
                'Jirón Angamos',
                'Jirón Arica',
                'Jirón Bolivar'
            ],
            'Nuevo Chimbote' => [
                'Av. Agraria',
                'Av. Anchoveta',
                'Av. Argentina',
                'Av. Brasil',
                'Av. Buenos Aires',
                'Av. Country',
                'Av. Industrial',
                'Av. La Marina',
                'Av. Pacífico',
                'Av. Perú',
                'Av. Santa',
                'Av. Universitaria',
                'Jr. Ayacucho',
                'Jr. Francisco Bolognesi',
                'Jr. Huaraz',
                'Jr. Independencia',
                'Jr. José Olaya',
                'Jr. Los Rosales',
                'Jr. Mariano Melgar',
                'Jr. Miguel Grau',
                'Jr. Samanco',
                'Jr. Tupac Amarú',
                'Calle Los Ficus',
                'Calle Los Jazmines',
                'Calle Los Laureles',
                'Psje. Los Álamos',
                'Psje. Los Pinos',
                'Psje. Los Rosales'
            ],
            'Independencia' => [
                'Av. Manco Capac',
                'Av. Centenario',
                'Av. Universitaria',
                'Av. Las Flores',
                'Jr. Las Orquideas',
                'Jr. Union',
                'Jr. El Pinal',
                'Jr. Carhuaz',
                'Jr. Sebastian de Aliste'
            ],
            'Cabana' => [
                'Av. Centenario',
                'Av. Grau',
                'Calle Embudo',
                'Calle Libertad',
                'Calle Lima',
                'Calle Miraflores',
                'Calle Porvenir',
                'Calle Trapitos',
                'Jr. Carmen Alto',
                'Jr. Cocharcas',
                'Jr. Concepcion',
                'Jr. Corongo'
            ],
            'Chimbote' => [
                'Av. de la Marina',
                'Av. Enrique Meiggs',
                'Av. Industrial',
                'Av. Jorge Chavez',
                'Av. José Balta',
                'Av. José Gálvez',
                'Av. José Pardo',
                'Av. Ladislao Espinar',
                'Jr. Aconcagua',
                'Jr. Aija',
                'Jr. Alfonso Ugarte',
                'Jr. Amazonas',
                'Jr. Ancash',
                'Jr. Angamos'
            ],
            'Pomabamba' => [
                'Jr. Arica',
                'Jr. Centenario',
                'Jr. Chachapoyas',
                'Jr. Huamachuco',
                'Jr. Santa Rosa',
                'Jr. Jorge Chavez',
                'Pj. Angelica',
                'Pj. Cirilo Vergaray',
                'Pj. Juan Vidal'
            ],
            'Sihuas' => [
                'Av. 28 de Julio',
                'Calle Amargura',
                'Calle Chirimoya',
                'Calle Jose Carlos Mariatequi',
                'Calle La Playa',
                'Jr. 9 de Enero',
                'Jr. Ancash',
                'Jr. Antonio Raymondi',
                'Jr. Atahualpa',
                'Jr. Bolivar',
                'Jr. San Francisco',
                'Jr. San Martin',
                'Jr. Señor de los Milagros',
                'Pj. Convento',
                'Pj. Sal si Puedes',
                'Pj. Virgen María de las Nieves'
            ],
            'Pampas' => [
                'Av. Consuzo',
                'Av. La Cantuta',
                'Calle Malecon Bermudez',
                'Jr. Ancash',
                'Jr. Arequipa',
                'Jr. Callao',
                'Jr. Camana',
                'Jr. Carabaya',
                'Jr. La Mar',
                'Jr. Leoncio Prado',
                'Jr. Los Altos',
                'Jr. Ucayali',
                'Jr. Unión'
            ],
            'Carhuaz' => [
                'Av. La Merced',
                'Av. Progreso',
                'Av. Santa Rosa',
                'Av. Soledad',
                'Jr. Bellavista',
                'Jr. Brasil',
                'Jr. Chaccha',
                'Jr. 2 de Mayo',
                'Jr. 28 de Julio',
                'Jr. Union',
                'Jr. Victoria',
                'Pj. 2 de Mayo',
                'Pj. Alameda',
                'Pj. Cesar Chavez'
            ],
            'Yungay' => [
                'Av. 28 de Julio',
                'Av. Arias Graziani',
                'Av. Confraternidad',
                'Av. Libertad',
                'Av. Llanganuco',
                'Av. Ignacio Amadeo Ramos Olivera',
                'Av. Santo Domingo',
                'Calle Campo Ferial',
                'Calle Enma Torres',
                'Calle Santo Domingo',
                'Calle Senz Pera',
                'Jr. 28 de Octubre',
                'Jr. Arias Guzman',
                'Jr. Dos de Mayo',
                'Jr. Progreso'
            ],
            'Conchucos' => [
                'Centro Poblado de Conchucos',
                'Centro Poblado de Putaga',
                'Centro Poblado de Marreros',
                'Centro Poblado de El Alto',
                'Centro Poblado de El Molino',
                'Centro Poblado de El Telar',
                'Centro Poblado de Sarsa',
                'Centro Poblado de Collis',
                'Centro Poblado de Manzana',
                'Centro Poblado de Quisuar',
                'Centro Poblado de Callipampa',
                'Centro Poblado de Pampa Grande',
                'Centro Poblado de Acapampa',
                'Centro Poblado de Corral Redondo'
            ],
            'Casma' => [
                'Av. Reina',
                'Av. Fernando Lomparte',
                'Av. Libertad',
                'Av. Bolivar',
                'Pj. Los Laureles',
                'Jr. Los Pinos',
                'Av. Nicolas de Pierola',
                'Av. Huaraz',
                'Av. Cesar Vallejo'
            ],
        ];

        $alergiasMedicas = [
            'Penicilina',
            'Aspirina',
            'Ibuprofeno',
            'Sulfonamidas',
            'Cefalosporinas',
            'AINES',
            'Morfina',
            'Codeína',
            'Tramadol',
            'Diclofenaco',
            'Paracetamol',
            'Amoxicilina',
            'Ciprofloxacino',
            'Metronidazol',
            'Yodo/Contraste radiológico',
            'Látex',
            'Anestesia local',
            'Mariscos',
            'Frutos secos',
        ];

        // Seleccionar género aleatorio
        $genero = fake()->randomElement(['masculino', 'femenino']);
        $nombres = $genero === 'masculino' ? $nombresMasculinos : $nombresFemeninos;

        // Seleccionar código IPRESS aleatorio
        $ipressCode = fake()->randomElement($ipressCodes);
        $location = $ipressLocation[$ipressCode];
        $distrito = $location['distrito'];
        $provincia = $location['provincia'];

        // Generar dirección según el código IPRESS
        if ($ipressCode === '000036306') {
            $direccion = fake()->randomElement($callesPorUbicacion['Conchucos']) . ', ' . $distrito . ', ' . $provincia . ', Ancash';
        } else {
            // Para los demás, generar dirección con número
            $calle = fake()->randomElement($callesPorUbicacion[$distrito]);
            $numero = fake()->numberBetween(100, 999);
            $direccion = $calle . ' N° ' . $numero . ', ' . $distrito . ', ' . $provincia . ', Ancash';
        }

        return [
            'ipress' => $ipressCode,
            'numero_ficha' => fake()->optional(0.8)->numerify('F-####-2024'),
            'apellidos' => fake()->randomElement($apellidos) . ' ' . fake()->randomElement($apellidos),
            'nombres' => fake()->randomElement($nombres) . ' ' . fake()->passthrough(fake()->randomElement($nombres)),
            'dni' => fake()->unique()->numerify('########'),
            'telefono' => fake()->optional(0.7)->numerify('9########'),
            'direccion' => $direccion,
            'email' => fake()->optional(0.8)->passthrough(fake()->userName() . '@gmail.com'),
            'fecha_ingreso' => fake()->dateTimeBetween('-3 years', 'now'),
            'fecha_nacimiento' => fake()->dateTimeBetween('-90 years', '-60 years'),
            'alergias' => fake()->optional(0.6)->randomElement($alergiasMedicas),
            'adulto_mayor_fragil' => fake()->randomElement(['No', 'Sí', null]),
        ];
    }
}
