<?php

namespace Database\Factories;

use App\Models\AdultoMayor;
use App\Models\Ipress;
use App\Models\User;
use Illuminate\Database\Eloquent\Factories\Factory;

class AdultoMayorFactory extends Factory
{
    protected $model = AdultoMayor::class;

    public function definition(): array
    {
        $apellidos = [
            'García',
            'Rodríguez',
            'González',
            'Fernández',
            'López',
            'Martínez',
            'Sánchez',
            'Pérez',
            'Gómez',
            'Martín',
            'Jiménez',
            'Ruiz',
            'Hernández',
            'Díaz',
            'Moreno',
            'Álvarez',
            'Muñoz',
            'Romero',
            'Alonso',
            'Gutiérrez',
            'Navarro',
            'Torres',
            'Domínguez',
            'Vázquez',
            'Ramos',
            'Gil',
            'Ramírez',
            'Serrano',
            'Blanco',
            'Suárez',
            'Molina',
            'Castro',
            'Ortiz',
            'Rubio',
            'Marín',
            'Sanz',
            'Iglesias',
            'Medina',
            'Garrido',
            'Cortés',
            'Castillo'
        ];

        $nombresMasculinos = [
            'José',
            'Antonio',
            'Juan',
            'Manuel',
            'Francisco',
            'Pedro',
            'Luis',
            'Miguel',
            'Ángel',
            'Carlos',
            'Ramón',
            'Vicente',
            'Rafael',
            'Fernando',
            'Enrique',
            'Alberto',
            'Roberto',
            'Ricardo',
            'Andrés',
            'Jorge',
            'Jesús',
            'Javier',
            'Raúl',
            'Sergio',
            'Arturo',
            'Héctor',
            'Julio',
            'Alejandro',
            'Gustavo',
            'Víctor',
            'Mario',
            'Óscar',
            'César',
            'Alfredo',
            'Ernesto',
            'Guillermo',
            'Tomás',
            'Martín',
            'Ignacio',
            'Felipe',
        ];

        $nombresFemeninos = [
            'María',
            'Rosa',
            'Carmen',
            'Juana',
            'Ana',
            'Isabel',
            'Teresa',
            'Dolores',
            'Francisca',
            'Josefa',
            'Concepción',
            'Pilar',
            'Mercedes',
            'Antonia',
            'Cristina',
            'Elena',
            'Julia',
            'Patricia',
            'Beatriz',
            'Silvia',
            'Margarita',
            'Gloria',
            'Lucía',
            'Victoria',
            'Raquel',
            'Susana',
            'Mónica',
            'Yolanda',
            'Angela',
            'Laura',
            'Alicia',
            'Graciela',
            'Catalina',
            'Cecilia',
            'Diana',
            'Martha',
            'Gladys',
            'Lidia',
            'Nélida',
            'Estela',
        ];

        // Datos de IPRESS disponibles
        $ipressData = [
            ['codigo' => '00009926', 'nombre' => 'POSTA MÉDICA PISCOBAMBA', 'distrito' => 'Piscobamba', 'provincia' => 'Mariscal Luzuriaga'],
            ['codigo' => '00009921', 'nombre' => 'CENTRO DE ATENCIÓN PRIMARIA II SAN JACINTO', 'distrito' => 'Nepeña', 'provincia' => 'Santa'],
            ['codigo' => '00009925', 'nombre' => 'POSTA MÉDICA PALLASCA', 'distrito' => 'Pallasca', 'provincia' => 'Pallasca'],
            ['codigo' => '00009204', 'nombre' => 'CENTRO MÉDICO HUARI', 'distrito' => 'Huari', 'provincia' => 'Huari'],
            ['codigo' => '00009920', 'nombre' => 'CENTRO MÉDICO CARAZ', 'distrito' => 'Caraz', 'provincia' => 'Huaylas'],
            ['codigo' => '00009059', 'nombre' => 'CENTRO MÉDICO HUARMEY', 'distrito' => 'Huarmey', 'provincia' => 'Huarmey'],
            ['codigo' => '00009055', 'nombre' => 'CENTRO MÉDICO COISHCO', 'distrito' => 'Coishco', 'provincia' => 'Santa'],
            ['codigo' => '00009054', 'nombre' => 'HOSPITAL I CONO SUR', 'distrito' => 'Nuevo Chimbote', 'provincia' => 'Santa'],
            ['codigo' => '00009053', 'nombre' => 'HOSPITAL II HUARAZ', 'distrito' => 'Independencia', 'provincia' => 'Huaraz'],
            ['codigo' => '00009924', 'nombre' => 'POSTA MÉDICA CABANA', 'distrito' => 'Cabana', 'provincia' => 'Pallasca'],
            ['codigo' => '00009047', 'nombre' => 'HOSPITAL III CHIMBOTE', 'distrito' => 'Chimbote', 'provincia' => 'Santa'],
            ['codigo' => '00009922', 'nombre' => 'CENTRO DE ATENCIÓN PRIMARIA II POMABAMBA', 'distrito' => 'Pomabamba', 'provincia' => 'Pomabamba'],
            ['codigo' => '000010013', 'nombre' => 'POLICLÍNICO DE COMPLEJIDAD CRECIENTE VICTOR PANTA RODRIGUEZ', 'distrito' => 'Chimbote', 'provincia' => 'Santa'],
            ['codigo' => '00009203', 'nombre' => 'CENTRO MÉDICO SIHUAS', 'distrito' => 'Sihuas', 'provincia' => 'Sihuas'],
            ['codigo' => '00009202', 'nombre' => 'POSTA MÉDICA PAMPAS', 'distrito' => 'Pampas', 'provincia' => 'Pallasca'],
            ['codigo' => '00009060', 'nombre' => 'CENTRO MÉDICO CARHUAZ', 'distrito' => 'Carhuaz', 'provincia' => 'Carhuaz'],
            ['codigo' => '00009923', 'nombre' => 'POSTA MÉDICA YUNGAY', 'distrito' => 'Yungay', 'provincia' => 'Yungay'],
            ['codigo' => '00009201', 'nombre' => 'POSTA MÉDICA CONCHUCOS', 'distrito' => 'Conchucos', 'provincia' => 'Pallasca'],
            ['codigo' => '00009057', 'nombre' => 'CENTRO MÉDICO CASMA', 'distrito' => 'Casma', 'provincia' => 'Casma'],
            ['codigo' => '000033542', 'nombre' => 'CAP II SAN JACINTO', 'distrito' => 'Nepeña', 'provincia' => 'Santa'],
            ['codigo' => '000036306', 'nombre' => 'POSTA MÉDICA CONCHUCOS', 'distrito' => 'Conchucos', 'provincia' => 'Pallasca'],
        ];

        // Calles por ubicación
        $callesPorUbicacion = [
            'Piscobamba' => [
                'Av. República de Suiza',
                'Calle San Andres',
                'Calle Santo Toribio',
                'Jr. Capac Yupanqui',
                'Jr. Convento',
                'Jr. Guaman Poma de Ayala',
                'Jr. Huancayo',
                'Jr. Manco Inca',
                'Jr. Manuel Arturo Odria',
                'Jr. Marcelino Orcaña',
                'Jr. Salas',
                'Jr. Tupac Yupanqui'
            ],
            'Pallasca' => [
                'Jr. Marañon',
                'Jr. San Martin',
                'Jr. Soledad',
                'Jr. Grau',
                'Jr. Amazonas',
                'Jr. Huallaga',
                'Jr. Comercio',
                'Jr. Trujillo'
            ],
            'Nepeña' => [
                'Avenida 28 de Julio',
                'Avenida El Comercio',
                'Avenida Iquitos',
                'Avenida Juan Velasco Alvarado',
                'Avenida Plaza de Armas',
                'Avenida Progreso',
                'Avenida Santa Rosa',
                'Calle Ancash',
                'Calle Augusto B. Leguía',
                'Jr. Ladislao Espinar',
                'Calle Hipolito Unanue',
                'Av. Solivin',
                'Calle Guillermo Campos',
                'Av. Daniel Alcides Carrion',
                'Calle Pedro Ruiz Gallo',
                'Calle Tupac Amaru'
            ],
            'Huari' => [
                'Avenida 14 de Junio',
                'Avenida Circunvalación',
                'Avenida San Bartolomé',
                'Jirón 24 de Agosto',
                'Jirón Adán Tello',
                'Jirón Ancash',
                'Jirón Libertad',
                'Jirón Leoncio Prado'
            ],
            'Caraz' => [
                'Av. Meza Arizona',
                'Av. Boulevard Llullan',
                'Av. Las Gardenias',
                'Av. Los Meandros',
                'Av. Palmira',
                'Av. Tumshukayko',
                'Jr. Antonio Raimondi',
                'Jr. Arequipa',
                'Jr. Bolognesi',
                'Jr. Camino Real',
                'Jr. Grau',
                'Jr. Jorge Chavez',
                'Jr. José Gálvez',
                'Jr. Kankas',
                'Jr. La Mar'
            ],
            'Huarmey' => [
                'Av. Aija',
                'Av. Alberto Reyes',
                'Av. Alfonso Ugarte',
                'Av. Garcilaso de la Vega',
                'Av. Olivar',
                'Av. Puerto Grande',
                'Calle Cesar Vallejo',
                'Calle Ernesto Reyna',
                'Calle Francisco Bolognesi',
                'Calle Gonzales Prada',
                'Calle Jose Santos Cocano',
                'Calle Manuel Scorza',
                'Calle María Graña',
                'Calle MIguel Grau'
            ],
            'Coishco' => [
                'Avenida Villa del Mar',
                'Calle Alfonso Ugarte',
                'Calle Bienaventurados',
                'Calle Buenos Aires',
                'Calle Coishco',
                'Calle D. Alcides Carrión',
                'Calle Huascar',
                'Jirón 28 de Julio',
                'Jirón Amazonas',
                'Jirón Ancash',
                'Jirón Angamos',
                'Jirón Arica',
                'Jirón Bolivar'
            ],
            'Nuevo Chimbote' => [
                'Av. Agraria',
                'Av. Anchoveta',
                'Av. Argentina',
                'Av. Brasil',
                'Av. Buenos Aires',
                'Av. Country',
                'Av. Industrial',
                'Av. La Marina',
                'Av. Pacífico',
                'Av. Perú',
                'Av. Santa',
                'Av. Universitaria',
                'Jr. Ayacucho',
                'Jr. Francisco Bolognesi',
                'Jr. Huaraz',
                'Jr. Independencia',
                'Jr. José Olaya',
                'Jr. Los Rosales',
                'Jr. Mariano Melgar',
                'Jr. Miguel Grau',
                'Jr. Samanco',
                'Jr. Tupac Amarú',
                'Calle Los Ficus',
                'Calle Los Jazmines',
                'Calle Los Laureles',
                'Psje. Los Álamos',
                'Psje. Los Pinos',
                'Psje. Los Rosales'
            ],
            'Independencia' => [
                'Av. Manco Capac',
                'Av. Centenario',
                'Av. Universitaria',
                'Av. Las Flores',
                'Jr. Las Orquideas',
                'Jr. Union',
                'Jr. El Pinal',
                'Jr. Carhuaz',
                'Jr. Sebastian de Aliste'
            ],
            'Cabana' => [
                'Av. Centenario',
                'Av. Grau',
                'Calle Embudo',
                'Calle Libertad',
                'Calle Lima',
                'Calle Miraflores',
                'Calle Porvenir',
                'Calle Trapitos',
                'Jr. Carmen Alto',
                'Jr. Cocharcas',
                'Jr. Concepcion',
                'Jr. Corongo'
            ],
            'Chimbote' => [
                'Av. de la Marina',
                'Av. Enrique Meiggs',
                'Av. Industrial',
                'Av. Jorge Chavez',
                'Av. José Balta',
                'Av. José Gálvez',
                'Av. José Pardo',
                'Av. Ladislao Espinar',
                'Jr. Aconcagua',
                'Jr. Aija',
                'Jr. Alfonso Ugarte',
                'Jr. Amazonas',
                'Jr. Ancash',
                'Jr. Angamos'
            ],
            'Pomabamba' => [
                'Jr. Arica',
                'Jr. Centenario',
                'Jr. Chachapoyas',
                'Jr. Huamachuco',
                'Jr. Santa Rosa',
                'Jr. Jorge Chavez',
                'Pj. Angelica',
                'Pj. Cirilo Vergaray',
                'Pj. Juan Vidal'
            ],
            'Sihuas' => [
                'Av. 28 de Julio',
                'Calle Amargura',
                'Calle Chirimoya',
                'Calle Jose Carlos Mariatequi',
                'Calle La Playa',
                'Jr. 9 de Enero',
                'Jr. Ancash',
                'Jr. Antonio Raymondi',
                'Jr. Atahualpa',
                'Jr. Bolivar',
                'Jr. San Francisco',
                'Jr. San Martin',
                'Jr. Señor de los Milagros',
                'Pj. Convento',
                'Pj. Sal si Puedes',
                'Pj. Virgen María de las Nieves'
            ],
            'Pampas' => [
                'Av. Consuzo',
                'Av. La Cantuta',
                'Calle Malecon Bermudez',
                'Jr. Ancash',
                'Jr. Arequipa',
                'Jr. Callao',
                'Jr. Camana',
                'Jr. Carabaya',
                'Jr. La Mar',
                'Jr. Leoncio Prado',
                'Jr. Los Altos',
                'Jr. Ucayali',
                'Jr. Unión'
            ],
            'Carhuaz' => [
                'Av. La Merced',
                'Av. Progreso',
                'Av. Santa Rosa',
                'Av. Soledad',
                'Jr. Bellavista',
                'Jr. Brasil',
                'Jr. Chaccha',
                'Jr. 2 de Mayo',
                'Jr. 28 de Julio',
                'Jr. Union',
                'Jr. Victoria',
                'Pj. 2 de Mayo',
                'Pj. Alameda',
                'Pj. Cesar Chavez'
            ],
            'Yungay' => [
                'Av. 28 de Julio',
                'Av. Arias Graziani',
                'Av. Confraternidad',
                'Av. Libertad',
                'Av. Llanganuco',
                'Av. Ignacio Amadeo Ramos Olivera',
                'Av. Santo Domingo',
                'Calle Campo Ferial',
                'Calle Enma Torres',
                'Calle Santo Domingo',
                'Calle Senz Pera',
                'Jr. 28 de Octubre',
                'Jr. Arias Guzman',
                'Jr. Dos de Mayo',
                'Jr. Progreso'
            ],
            'Conchucos' => [
                'Centro Poblado de Conchucos',
                'Centro Poblado de Putaga',
                'Centro Poblado de Marreros',
                'Centro Poblado de El Alto',
                'Centro Poblado de El Molino',
                'Centro Poblado de El Telar',
                'Centro Poblado de Sarsa',
                'Centro Poblado de Collis',
                'Centro Poblado de Manzana',
                'Centro Poblado de Quisuar',
                'Centro Poblado de Callipampa',
                'Centro Poblado de Pampa Grande',
                'Centro Poblado de Acapampa',
                'Centro Poblado de Corral Redondo'
            ],
            'Casma' => [
                'Av. Reina',
                'Av. Fernando Lomparte',
                'Av. Libertad',
                'Av. Bolivar',
                'Pj. Los Laureles',
                'Jr. Los Pinos',
                'Av. Nicolas de Pierola',
                'Av. Huaraz',
                'Av. Cesar Vallejo'
            ],
        ];

        $alergiasMedicas = [
            'Penicilina',
            'Aspirina',
            'Ibuprofeno',
            'Sulfonamidas',
            'Cefalosporinas',
            'AINES',
            'Morfina',
            'Codeína',
            'Tramadol',
            'Diclofenaco',
            'Paracetamol',
            'Amoxicilina',
            'Ciprofloxacino',
            'Metronidazol',
            'Yodo/Contraste radiológico',
            'Látex',
            'Anestesia local',
            'Mariscos',
            'Frutos secos',
        ];

        // Seleccionar género aleatorio
        $genero = fake()->randomElement(['masculino', 'femenino']);
        $nombres = $genero === 'masculino' ? $nombresMasculinos : $nombresFemeninos;

        // Seleccionar IPRESS aleatorio y crear/obtener registro
        $ipressDataSelected = fake()->randomElement($ipressData);
        $ipress = Ipress::firstOrCreate(
            ['codigo_ipress' => $ipressDataSelected['codigo']],
            [
                'nombre' => $ipressDataSelected['nombre'],
                'distrito' => $ipressDataSelected['distrito'],
                'provincia' => $ipressDataSelected['provincia'],
                'departamento' => 'Ancash',
                'activo' => true,
            ]
        );

        $distrito = $ipress->distrito;
        $provincia = $ipress->provincia;

        // Generar dirección según el código IPRESS
        if ($ipress->codigo_ipress === '000036306') {
            $direccion = fake()->randomElement($callesPorUbicacion['Conchucos']) . ', ' . $distrito . ', ' . $provincia . ', Ancash';
        } else {
            // Para los demás, generar dirección con número
            $calle = fake()->randomElement($callesPorUbicacion[$distrito]);
            $numero = fake()->numberBetween(100, 999);
            $direccion = $calle . ' N° ' . $numero . ', ' . $distrito . ', ' . $provincia . ', Ancash';
        }

        return [
            'ipress_id' => $ipress->id,
            'numero_ficha' => fake()->optional(0.8)->numerify('F-####-2024'),
            'apellidos' => fake()->randomElement($apellidos) . ' ' . fake()->randomElement($apellidos),
            'nombres' => fake()->randomElement($nombres) . ' ' . fake()->passthrough(fake()->randomElement($nombres)),
            'dni' => fake()->unique()->numerify('########'),
            'telefono' => fake()->optional(0.7)->numerify('9########'),
            'direccion' => $direccion,
            'email' => fake()->optional(0.8)->passthrough(fake()->userName() . '@gmail.com'),
            'fecha_ingreso' => fake()->dateTimeBetween('-3 years', 'now'),
            'fecha_nacimiento' => fake()->dateTimeBetween('-90 years', '-60 years'),
            'alergias' => fake()->optional(0.6)->randomElement($alergiasMedicas),
            'adulto_mayor_fragil' => fake()->randomElement(['No', 'Sí', null]),
        ];
    }
}
